import type { GrantProgram } from "./domain";

const observedAt = "2026-07-13";

export const grantCatalog: GrantProgram[] = [
  {
    id: "kstartup-2026-integrated",
    title: "2026년 창업지원사업 통합공고",
    organizer: "중소벤처기업부 · K-Startup",
    supportType: "seed_funding",
    maxSupportWon: 100_000_000,
    applicationWindow: "공고별 상이 · bizinfo.go.kr에서 확인",
    officialUrl: "https://www.bizinfo.go.kr/sii/siia/selectSIIA200Detail.do?pblancId=PBLN_000000000116904",
    observedAt,
    summary: "예비·초기·도약 단계 창업자를 위한 통합 공고 허브입니다. 사업별 세부 요건을 반드시 확인해야 합니다.",
    targetFounder: ["예비창업자", "초기창업자", "도약창업자"],
    targetArchetypes: ["digital_service", "ecommerce", "local_retail", "professional_service", "manufacturing"],
    minTeamSize: 1,
    maxTeamSize: null,
    requiresIncorporation: null,
    excludedKeywords: ["대출", "보증만"],
    requiredEvidence: ["사업계획서", "팀 구성", "사업자등록 또는 예비창업 확인"],
  },
  {
    id: "pre-startup-package",
    title: "2026년 예비창업패키지",
    organizer: "창업진흥원",
    supportType: "seed_funding",
    maxSupportWon: 80_000_000,
    applicationWindow: "2026년 모집 종료 · 2026-03-24 수정 공고 기준",
    officialUrl: "https://www.mss.go.kr/site/smba/ex/bbs/View.do?bcIdx=1066579&cbIdx=310",
    observedAt,
    summary: "사업자등록 전 예비창업자 대상 사업화 자금과 멘토링을 지원합니다.",
    targetFounder: ["예비창업자"],
    targetArchetypes: ["digital_service", "ecommerce", "local_retail", "professional_service", "manufacturing"],
    minTeamSize: 1,
    maxTeamSize: 5,
    requiresIncorporation: false,
    excludedKeywords: ["의료", "금융중개"],
    requiredEvidence: ["예비창업 확인", "사업계획서", "팀 역량 증빙"],
  },
  {
    id: "early-startup-package",
    title: "2026년 초기창업패키지(일반형)",
    organizer: "창업진흥원",
    supportType: "seed_funding",
    maxSupportWon: 100_000_000,
    applicationWindow: "2026-01-23 ~ 2026-02-13 · 모집 종료",
    officialUrl: "https://www.mss.go.kr/site/smba/ex/bbs/View.do?bcIdx=1065015&cbIdx=310&parentSeq=1065015",
    observedAt,
    summary: "창업 3년 이내 기업의 제품·서비스 고도화와 초기 매출 확보를 지원합니다.",
    targetFounder: ["초기창업자"],
    targetArchetypes: ["digital_service", "ecommerce", "local_retail", "professional_service", "manufacturing"],
    minTeamSize: 1,
    maxTeamSize: null,
    requiresIncorporation: true,
    excludedKeywords: [],
    requiredEvidence: ["사업자등록증", "매출 또는 검증 지표", "사업계획서"],
  },
  {
    id: "smba-policy-fund",
    title: "소상공인 정책자금",
    organizer: "소상공인시장진흥공단",
    supportType: "loan_guarantee",
    maxSupportWon: 70_000_000,
    applicationWindow: "상시 · 업종·지역별 한도 상이",
    officialUrl: "https://www.semas.or.kr/web/smba/main/main.do",
    observedAt,
    summary: "매장·소규모 서비스업의 운영자금과 시설자금을 저금리로 지원합니다.",
    targetFounder: ["초기창업자", "소상공인"],
    targetArchetypes: ["local_retail", "professional_service", "ecommerce"],
    minTeamSize: 1,
    maxTeamSize: null,
    requiresIncorporation: true,
    excludedKeywords: ["플랫폼만", "투자유치만"],
    requiredEvidence: ["사업자등록증", "매출·세금계산서", "임대차 또는 운영 증빙"],
  },
  {
    id: "youth-startup-academy",
    title: "청년창업사관학교",
    organizer: "중소벤처기업부",
    supportType: "mentoring",
    maxSupportWon: 100_000_000,
    applicationWindow: "연 1회 전후 · 연령 요건 확인",
    officialUrl: "https://www.k-startup.go.kr/web/contents/bizpbanc-ongoing.do",
    observedAt,
    summary: "39세 이하 청년 창업자 대상 집중 멘토링과 사업화 자금을 연계합니다.",
    targetFounder: ["예비창업자", "초기창업자"],
    targetArchetypes: ["digital_service", "ecommerce", "local_retail", "professional_service", "manufacturing"],
    minTeamSize: 1,
    maxTeamSize: 5,
    requiresIncorporation: null,
    excludedKeywords: [],
    requiredEvidence: ["연령 증빙", "창업 경험·역량", "사업계획서"],
  },
  {
    id: "regional-smallbiz-voucher",
    title: "지역형 소상공인 이용권·전문 상담",
    organizer: "지자체 · 소상공인시장진흥공단",
    supportType: "marketing",
    maxSupportWon: 5_000_000,
    applicationWindow: "시·도별 상이",
    officialUrl: "https://www.sbiz.or.kr/",
    observedAt,
    summary: "지역 소상공인의 홍보·전문 상담 비용을 이용권 형태로 지원합니다. 지역 거점 확인이 필요합니다.",
    targetFounder: ["소상공인", "초기창업자"],
    targetArchetypes: ["local_retail", "professional_service"],
    minTeamSize: 1,
    maxTeamSize: null,
    requiresIncorporation: true,
    excludedKeywords: ["온라인만"],
    requiredEvidence: ["사업자등록증", "지역 사업장 증빙", "매출 또는 운영 증빙"],
  },
  {
    id: "leap-startup-package",
    title: "창업도약패키지",
    organizer: "중소벤처기업부 · 창업진흥원",
    supportType: "seed_funding",
    maxSupportWon: 300_000_000,
    applicationWindow: "연 1~2회 모집 · 도약 단계 공고 확인",
    officialUrl: "https://www.k-startup.go.kr/web/contents/bizpbanc-ongoing.do",
    observedAt,
    summary: "창업 3~7년 기업의 성장·해외진출·제품 고도화를 지원합니다.",
    targetFounder: ["도약창업자"],
    targetArchetypes: ["digital_service", "ecommerce", "manufacturing", "professional_service"],
    minTeamSize: 2,
    maxTeamSize: null,
    requiresIncorporation: true,
    excludedKeywords: [],
    requiredEvidence: ["사업자등록증", "매출·성장 지표", "사업계획서", "팀 구성"],
  },
  {
    id: "tips-rnd",
    title: "민간투자 연계 기술개발(TIPS R&D) 창업지원",
    organizer: "중소벤처기업부",
    supportType: "seed_funding",
    maxSupportWon: 500_000_000,
    applicationWindow: "전문운영사·평가 일정 별도 공고",
    officialUrl: "https://www.jointips.or.kr/",
    observedAt,
    summary: "기술 기반 창업팀의 R&D와 사업화를 연계 지원합니다.",
    targetFounder: ["예비창업자", "초기창업자"],
    targetArchetypes: ["digital_service", "manufacturing"],
    minTeamSize: 2,
    maxTeamSize: null,
    requiresIncorporation: null,
    excludedKeywords: ["단순 유통", "중개만"],
    requiredEvidence: ["기술·지식재산 설명", "연구개발(R&D) 계획", "팀 역량", "사업계획서"],
  },
  {
    id: "kibo-tech-guarantee",
    title: "기술보증기금 보증",
    organizer: "기술보증기금",
    supportType: "loan_guarantee",
    maxSupportWon: 200_000_000,
    applicationWindow: "상시 · 기술평가·보증 한도 상이",
    officialUrl: "https://www.kibo.or.kr/",
    observedAt,
    summary: "기술력을 보유한 중소기업의 시설·운영자금 대출 보증을 지원합니다.",
    targetFounder: ["초기창업자", "도약창업자", "소상공인"],
    targetArchetypes: ["digital_service", "manufacturing", "professional_service", "ecommerce"],
    minTeamSize: 1,
    maxTeamSize: null,
    requiresIncorporation: true,
    excludedKeywords: [],
    requiredEvidence: ["기술·서비스 설명", "재무제표 또는 매출 증빙", "사업계획서"],
  },
  {
    id: "kodit-credit-guarantee",
    title: "신용보증기금 보증",
    organizer: "신용보증기금",
    supportType: "loan_guarantee",
    maxSupportWon: 100_000_000,
    applicationWindow: "상시 · 업종·신용등급별 차등",
    officialUrl: "https://www.kodit.or.kr/",
    observedAt,
    summary: "담보·신용이 부족한 사업자의 운영·시설자금 대출을 보증합니다.",
    targetFounder: ["초기창업자", "소상공인"],
    targetArchetypes: ["local_retail", "professional_service", "ecommerce", "digital_service"],
    minTeamSize: 1,
    maxTeamSize: null,
    requiresIncorporation: true,
    excludedKeywords: [],
    requiredEvidence: ["사업자등록증", "매출·거래 증빙", "보증·대출 신청서"],
  },
  {
    id: "women-pre-startup",
    title: "여성예비창업자 지원",
    organizer: "여성기업종합지원센터",
    supportType: "mentoring",
    maxSupportWon: 50_000_000,
    applicationWindow: "연간 공고 · 성별·예비창업 요건 확인",
    officialUrl: "https://www.k-startup.go.kr/web/contents/bizpbanc-ongoing.do",
    observedAt,
    summary: "여성 예비·초기 창업자 대상 멘토링·사업화 자금을 지원합니다.",
    targetFounder: ["예비창업자", "초기창업자"],
    targetArchetypes: ["digital_service", "ecommerce", "local_retail", "professional_service"],
    minTeamSize: 1,
    maxTeamSize: 5,
    requiresIncorporation: false,
    excludedKeywords: [],
    requiredEvidence: ["여성 창업자 증빙", "사업계획서", "팀 역량"],
  },
  {
    id: "data-voucher-ai",
    title: "데이터바우처(인공지능·데이터 활용)",
    organizer: "과학기술정보통신부",
    supportType: "marketing",
    maxSupportWon: 30_000_000,
    applicationWindow: "연 1~2회 · 바우처 유형별 상이",
    officialUrl: "https://www.data.go.kr/",
    observedAt,
    summary: "데이터 구매·가공·인공지능 모델 개발 비용을 이용권 형태로 지원합니다.",
    targetFounder: ["초기창업자", "도약창업자"],
    targetArchetypes: ["digital_service", "ecommerce", "manufacturing"],
    minTeamSize: 1,
    maxTeamSize: null,
    requiresIncorporation: true,
    excludedKeywords: [],
    requiredEvidence: ["데이터 활용 계획", "사업자등록증", "과제 수행 계획서"],
  },
];

export function catalogObservedAt() {
  return observedAt;
}
