/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 5f8418c83267eb0a3ac0a5a95005c867)
interface __BaseEnv_CloudflareEnv {
	ASSETS: Fetcher;
	OPENAI_MODEL: "gpt-5.6-sol";
	PERSISTENCE_MODE: string;
	PAYMENTS_ENABLED: string;
	ADMIN_CHAT_PASSWORD: string;
	SUPABASE_URL: string;
	SUPABASE_SERVICE_ROLE_KEY: string;
	WORKER_SELF_REFERENCE: Service<typeof import("./cloudflare-worker").default>;
	DRAFT_PACKAGE_WORKFLOW: Workflow<Parameters<import("./cloudflare-worker").DraftPackageWorkflow['run']>[0]['payload']>;
	DIRECT_PLAN_WORKFLOW: Workflow<Parameters<import("./cloudflare-worker").DirectPlanWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./cloudflare-worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENAI_MODEL" | "PERSISTENCE_MODE" | "PAYMENTS_ENABLED" | "ADMIN_CHAT_PASSWORD" | "SUPABASE_URL" | "SUPABASE_SERVICE_ROLE_KEY">> {}
}
