import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { readFileSync } from "node:fs";
import { performance } from "node:perf_hooks";
import { renderToStaticMarkup } from "react-dom/server";
import type { CoachState } from "../lib/plan-builder/coach";
import type { ServerPlan } from "../lib/plan-builder/plan-server-store";
import type { IntakeCandidate, IntakeCommand, IntakeSnapshot } from "../lib/plan-builder/intake-types";
import { createIntake, intakeSnapshot } from "../lib/plan-builder/intake-core";
import { structureQuestions, coreQuestions, detailQuestions, intakeSectorOptions } from "../lib/plan-builder/intake-questions";
import { assembleHybridText, candidateConflict, customCandidateDraftKey, optionGroups, selectedCount, stepVisible, withCount, draftKey, emptyAnswer, emptyDraft, entryMessage, hasExclusiveOptions, isHybridQuestion, isPrefillQuestion, needsPolling, parseDraft, periodDates, periodPresetRange, persistDraft, plainText, previewIntakeAnswer, readIntakePayload, readableFinancialSummary, seedAnswerDraft, settleDraft, shouldAcceptSnapshot, suggestedIntakeIndustry, summaryAnswerText, toggleChip, typedChoiceAnswer, typedEntryCommand, unfinishedAnswerText, unmatchedPieces } from "../app/plan/chat/intake-ui/model";
import { amountRanges, CHIP_GROUPS, numberPresets, sectorChipOptions } from "../lib/plan-builder/intake-options";
import type { IntakeQuestion } from "../lib/plan-builder/intake-questions";
import { intakeValueLabel } from "../lib/plan-builder/intake-core";
import { needsEntryConfirmation, routeComposerInput } from "../app/plan/chat/intake-ui/model";
import { readChatResponse } from "../lib/http/read-chat-response";

const scope = "test-owner-guest";
const id = "plan_ui-fixture";
const at = "2026-09-16T03:00:00.000Z";
const command = (overrides: Partial<IntakeCommand> = {}): IntakeCommand => ({ action: "answer", planId: id, requestId: "e72bf3c0-70de-49f3-9cb7-c322290f530a", revision: 2, questionId: "business", value: "소규모 매장의 예약 업무를 돕는 소프트웨어", ...overrides });

function fixture(mode: "exploring" | "startup" | "operating" = "startup"): IntakeSnapshot {
  const coach: CoachState = { version: "fixture", revision: 2, documentRevision: 1, stage: mode, depth: "quick", fields: [], messages: [], ready: false, suggestions: [], business: { name: "내 사업 구상", description: "", role: "", industry: "", region: "", stage: "사업 기획" } };
  const plan: ServerPlan = { id, title: "내 사업 구상", planType: "일반 사업계획서", createdAt: at, updatedAt: at, sections: {}, answers: {} };
  return intakeSnapshot(plan, coach, createIntake(coach, mode, at));
}

async function main() {
  const original = fixture();
  for (const text of ["카페가 괜찮을까요?", "안녕하세요", "예전에 카페를 운영했어요", "예산: 100만원 고객: 직장인"]) assert.equal(needsEntryConfirmation(text), true, text);
  assert.equal(needsEntryConfirmation("동네 카페를 운영 중이에요"), false);
  const customer = original.questions.find(q => q.id === "customer")!;
  assert.deepEqual(routeComposerInput(original, customer, "인근 직장인"), { kind: "answer", questionId: "customer", value: "인근 직장인" });
  assert.deepEqual(routeComposerInput(original, customer, "대학생과 직장인 중 누구부터 공략할까요?"), { kind: "note", intent: "question" });
  assert.equal(routeComposerInput(original, customer, "고객: 직장인 가격: 3만원").kind, "clarify");
  assert.equal(routeComposerInput(original, customer, "네").kind, "clarify");
  assert.deepEqual(routeComposerInput(original, customer, "아직 미정"), { kind: "answer", questionId: "customer", value: null, unknown: true });
  assert.equal(routeComposerInput(original, original.nextQuestion!, "세상에 없는 복합 사업").kind, "clarify");
  assert.deepEqual(routeComposerInput(original, original.nextQuestion!, "카페"), { kind: "answer", questionId: "industry", value: "food_beverage" });
  for (const response of [new Response("", { status: 500 }), new Response("<html>proxy failed</html>", { status: 502 }), new Response("{"), new Response("null")]) {
    await assert.rejects(readChatResponse(response), error => error instanceof Error && /입력은 그대로/.test(error.message) && !/Unexpected|JSON|proxy/.test(error.message));
  }
  assert.deepEqual(await readChatResponse(Response.json({ plan: null, enabled: true })), { plan: null, enabled: true });
  const noteDraft = { ...emptyDraft(), answers: { customer: { ...emptyAnswer(), text: "누구부터 공략할까요?" } } };
  const notePending = { command: command({ action: "note", message: "누구부터 공략할까요?" }), composer: { text: "누구부터 공략할까요?", mode: "answer" as const, questionId: "customer" } };
  assert.equal(settleDraft(noteDraft, notePending).answers.customer, undefined);
  assert.equal(settleDraft({ ...noteDraft, answers: { customer: { ...emptyAnswer(), text: "저장 중 추가 입력" } } }, notePending).answers.customer.text, "저장 중 추가 입력");
  // Spec §3.3: month presets cover completed months only; "올해" runs to today; dates are Asia/Seoul.
  assert.equal(periodPresetRange("3m", new Date(2026, 8, 16)), "2026-06-01 / 2026-08-31");
  assert.equal(periodPresetRange("last", new Date(2026, 2, 31)), "2026-02-01 / 2026-02-28", "지난달은 전월 1일부터 말일까지");
  assert.equal(periodPresetRange("12m", new Date(2026, 0, 15)), "2025-01-01 / 2025-12-31");
  assert.equal(periodPresetRange("6m", new Date(2026, 8, 16)), "2026-03-01 / 2026-08-31");
  assert.equal(periodPresetRange("year", new Date(2026, 8, 16)), "2026-01-01 / 2026-09-16");
  assert.equal(periodPresetRange("lastYear", new Date(2026, 8, 16)), "2025-01-01 / 2025-12-31");
  assert.equal(periodPresetRange("year", new Date("2026-09-15T16:00:00Z")), "2026-01-01 / 2026-09-16", "16:00Z is already the 16th in Seoul");
  assert.deepEqual(periodDates("2026-01-01 / 2026-06-30"), ["2026-01-01", "2026-06-30"]);
  assert.equal(periodDates("지난달"), null);
  assert.equal(intakeValueLabel(original.nextQuestion!, ["b2b_service", "software"]), "기업 서비스, 소프트웨어 · 플랫폼", "복수 선택은 라벨로 표시");
  assert.equal(intakeValueLabel(original.nextQuestion!, "food_beverage"), "카페 · 음식점");
  assert.equal(intakeValueLabel({ options: undefined }, "자유 답변"), "자유 답변");
  assert.deepEqual(typedEntryCommand(" 2d게임 만들어주는 웹사이트 "), { action: "start", mode: "startup", questionId: "business", value: "2d게임 만들어주는 웹사이트" });
  assert.deepEqual(typedEntryCommand("아이디어가 없어요"), { action: "start", mode: "exploring" });
  assert.deepEqual(typedEntryCommand("사업을 운영 중이에요"), { action: "start", mode: "operating" });
  assert.equal(typedEntryCommand("작은 카페를 운영 중이에요").mode, "operating");
  assert.equal(typedEntryCommand("카페를 운영 중인 건 아니에요").mode, "startup");
  assert.equal(entryMessage({ memo: "이미 보낸 내용", introMessage: "이미 보낸 내용" }), "이미 보낸 내용");
  assert.equal(entryMessage({ memo: "추가 내용", introMessage: "이전 내용" }), "이전 내용\n추가 내용");
  assert.equal(typedChoiceAnswer(original, original.nextQuestion!, "소프트웨어"), "software");
  assert.equal(typedChoiceAnswer(original, original.nextQuestion!, "카페"), "food_beverage");
  assert.equal(typedChoiceAnswer(original, original.nextQuestion!, "무슨 업종인지 잘 모르겠어요"), undefined);
  assert.deepEqual(typedChoiceAnswer(fixture("exploring"), fixture("exploring").nextQuestion!, "소프트웨어, 카페"), ["software", "food_beverage"]);
  const originalJson = JSON.stringify(original);
  const businessSnapshot = (text: string) => previewIntakeAnswer(original, command({ value: text }))!;
  for (const [text, expected] of [
    ["50만원으로 SNS컨설팅", "b2b_service"],
    ["2d게임 만들어주는 웹사이트", "software"],
    ["동네 커피 카페", "food_beverage"],
    ["스마트스토어에서 생활용품 온라인 판매", "retail_commerce"],
    ["맞춤 가구 제조 공장", "manufacturing"],
    ["40만원으로 SNS 강의 수업", "education"],
    ["방문 청소 서비스", "local_service"],
    ["모임 공간 대관", "space_hospitality"],
    ["지역 물류 배송 대행", "logistics"],
    ["브랜드 영상 촬영", "content_media"],
    ["아직 이름 없는 새로운 사업", null],
    ["카페 사장님을 위한 SNS 컨설팅", "b2b_service"],
    ["소프트웨어 개발 강의", "education"],
    ["홈페이지 제작 대행", "b2b_service"],
    ["카페 고객 관리 앱", "software"],
    ["카페와 온라인 쇼핑몰을 함께 운영", null],
    ["소프트웨어가 아닌 카페", null],
    ["카페 그리고 교육", null],
  ] as const) assert.equal(suggestedIntakeIndustry(businessSnapshot(text))?.value ?? null, expected, text);
  const suggestedBusiness = businessSnapshot("50만원으로 SNS컨설팅");
  const beforeSuggestion = JSON.stringify(suggestedBusiness);
  assert.equal(suggestedIntakeIndustry(suggestedBusiness)?.label, "기업 서비스");
  assert.equal(JSON.stringify(suggestedBusiness), beforeSuggestion, "A recommendation does not confirm or save an industry");
  assert.equal(suggestedBusiness.intake.answers.industry, undefined);
  assert.equal(suggestedIntakeIndustry(original), null);
  assert.equal(suggestedIntakeIndustry({ ...original, coach: { ...original.coach, fields: [{ key: "business", value: "커피 카페", basis: "proposal", quote: "", messageId: "proposal-only" }] } }), null, "Unconfirmed AI suggestions are not classification evidence");
  assert.equal(suggestedIntakeIndustry({ ...suggestedBusiness, coach: { ...suggestedBusiness.coach, fields: [...suggestedBusiness.coach.fields, { key: "offer", value: "커피 판매", basis: "user", quote: "커피 판매", messageId: "confirmed-offer" }] } }), null, "Conflicting confirmed business and offer require a manual choice");
  const preview = previewIntakeAnswer(original, command({ questionId: "industry", value: "software" }))!;
  assert.equal(preview.nextQuestion?.id, "business");
  assert.equal(preview.coreAnswered, 1);
  assert.equal(preview.coach.revision, 3);
  assert.equal(JSON.stringify(original), originalJson, "Local preview must not mutate the server snapshot");
  assert.equal(previewIntakeAnswer(original, command({ revision: 1 })), null, "Do not preview an uncertain request against a different revision");
  const skipped = previewIntakeAnswer(original, command({ questionId: "industry", value: null, unknown: true }))!;
  assert.equal(skipped.nextQuestion?.id, "business");
  assert.equal(skipped.intake.answers.industry.status, "unknown");
  assert.throws(() => previewIntakeAnswer(original, command({ questionId: "industry", value: "invented" })));
  assert.throws(() => previewIntakeAnswer(fixture("operating"), command({ questionId: "period", value: "2026-12-31 / 2026-01-01" })));
  assert.throws(() => previewIntakeAnswer(original, command({ questionId: "hoursPerWeek", value: 169 })));
  const zero = previewIntakeAnswer(original, command({ questionId: "budget", value: "0" }))!;
  assert.equal(zero.intake.answers.budget.status, "answered", "Zero is a real answer, not unknown");
  assert.equal(zero.coach.fields.find(field => field.key === "budget")?.value, "0원");

  const timings: number[] = [];
  for (let index = 0; index < 100; index++) {
    const start = performance.now();
    previewIntakeAnswer(original, command({ questionId: "industry", value: "software" }));
    timings.push(performance.now() - start);
  }
  const p95 = timings.sort((a, b) => a - b)[94];
  assert.ok(p95 < 300, `Next-question local preview p95 ${p95.toFixed(1)}ms exceeds 300ms`);

  const answer = { text: "원래 입력", selected: [], custom: false };
  const pending = { command: command(), answer };
  const draft = { ...emptyDraft(), ownerScope: scope, answers: { business: answer }, pending };
  const encoded = JSON.stringify(draft);
  assert.equal(parseDraft(encoded, id, scope).pending?.command.requestId, pending.command.requestId);
  assert.equal(parseDraft(encoded, id, "different-account").pending, null);
  assert.equal(parseDraft(encoded, "different-plan", scope).pending, null);
  assert.equal(parseDraft(encoded, id).pending, null, "Never restore unscoped pending requests");
  assert.equal(parseDraft("bad json", id, scope).pending, null);
  assert.notEqual(draftKey(id, scope), draftKey(id, "another-owner"));
  assert.notEqual(draftKey(id, scope), draftKey("another-plan", scope));
  const memory = new Map();
  assert.equal(persistDraft(draftKey(id, scope), draft, memory, () => { throw new Error("Storage blocked"); }), false);
  assert.equal(memory.get(draftKey(id, scope))?.answers.business.text, "원래 입력", "A blocked storage getter must retain the in-memory draft");
  assert.equal(persistDraft(draftKey(id, scope), draft, memory, () => ({ setItem: () => { throw new Error("Quota exceeded"); } })), false);
  assert.equal(memory.get(draftKey(id, scope))?.pending.command.requestId, pending.command.requestId);
  assert.equal(persistDraft(draftKey(id, scope), draft, memory, () => ({ setItem: () => {} })), true);
  const settled = settleDraft(draft, pending);
  assert.equal(settled.answers.business, undefined);
  assert.equal(settled.pending, null);
  const typedDuringSave = settleDraft({ ...draft, answers: { business: { ...answer, text: "전송 후 바꾼 내용" }, customer: { ...answer, text: "다음 질문 입력" } } }, pending);
  assert.equal(typedDuringSave.answers.business.text, "전송 후 바꾼 내용");
  assert.equal(typedDuringSave.answers.customer.text, "다음 질문 입력");
  assert.equal(typedDuringSave.editingId, "business");
  const nextQuestionDraft = settleDraft({ ...draft, answers: { business: answer, customer: { ...answer, text: "입력 중인 다음 답변" } } }, pending);
  assert.equal(nextQuestionDraft.answers.customer.text, "입력 중인 다음 답변");
  assert.equal(settleDraft({ ...draft, editingId: "business" }, pending).editingId, null, "A saved existing answer releases its editing question");
  assert.equal(settleDraft({ ...draft, editingId: "customer" }, pending).editingId, "customer", "Do not override a user-selected editor while saving another question");
  const custom = { text: "후보 대신 직접 구상", selected: [], custom: true };
  assert.equal(settleDraft({ ...draft, answers: { candidate: custom } }, { command: command(), answer: custom }).answers.candidate, undefined);
  assert.equal(customCandidateDraftKey("business", true), "candidate");
  assert.equal(customCandidateDraftKey("customer", true), "customer", "Only the candidate toggle remaps its draft key; hybrid drafts never move to candidate");
  assert.equal(customCandidateDraftKey("business", false), "business");
  const hybridPending = { command: command({ questionId: "customer", value: "주거 상권 가족·주부" }), answer: { text: "주거 상권 가족·주부", selected: ["가족"], custom: true } };
  assert.equal(settleDraft({ ...draft, answers: { customer: hybridPending.answer } }, hybridPending).answers.customer, undefined, "A stray custom flag on a hybrid answer must not leave the draft behind under candidate");
  assert.equal(settleDraft({ ...draft, memo: "새 메모" }, { command: command({ action: "message" }), text: "이전 메모" }).memo, "새 메모");
  const intro = { ...emptyDraft(), ownerScope: scope, introMessage: "커피 가게를 시작하고 싶어요" };
  assert.equal(parseDraft(JSON.stringify(intro), null, scope).introMessage, intro.introMessage);
  assert.equal(settleDraft(intro, { command: command({ action: "start" }) }).introMessage, intro.introMessage, "Selecting a stage must not discard the first typed message");
  assert.equal(settleDraft(intro, { command: command({ action: "message" }), text: intro.introMessage }).introMessage, null);
  assert.equal(settleDraft(intro, { command: command({ action: "message" }), text: "다른 메시지" }).introMessage, intro.introMessage);
  const typedPending = { command: command({ action: "start" }), text: intro.introMessage, intro: intro.introMessage };
  const typedSettled = settleDraft({ ...intro, memo: intro.introMessage! }, typedPending);
  assert.equal(typedSettled.memo, ""); assert.equal(typedSettled.introMessage, null);
  assert.equal(settleDraft({ ...intro, memo: "저장 중에 추가 입력" }, typedPending).memo, "저장 중에 추가 입력");
  assert.equal(settleDraft({ ...emptyDraft(), memo: "소프트웨어" }, { command: command({ questionId: "industry", value: "software" }), text: "소프트웨어" }).memo, "");

  const running = { id: "job", runId: "run", kind: "extract" as const, status: "running" as const, noteIds: [], baseValues: {}, baseDocumentRevision: 1, updatedAt: at };
  const active = { ...original, intake: { ...original.intake, job: running } };
  assert.equal(needsPolling(active), true);
  const completed = { ...active, intake: { ...active.intake, job: { ...running, status: "complete" as const } } };
  assert.equal(needsPolling(completed), false);
  assert.equal(needsPolling({ ...completed, intake: { ...completed.intake, notes: [{ id: "queued", text: "메모", at, status: "queued" }] } }), false, "Deferred notes do not start polling or paid extraction on their own");
  assert.equal(needsPolling({ ...completed, intake: { ...completed.intake, notes: [{ id: "failed", text: "메모", at, status: "failed" }] } }), false);
  assert.equal(needsPolling({ ...completed, pendingExtraction: true }), false, "Pending review is not an active job");

  const candidate: IntakeCandidate = { id: "candidate1", fieldKey: "business", value: "추출한 새 값", quote: "메모의 원문", noteId: "note1", baseValue: "이전 값", status: "pending" };
  const withBusiness = { ...original, coach: { ...original.coach, fields: [{ key: "business" as const, value: "직접 수정한 값", basis: "user" as const, messageId: "answer1", quote: "직접 수정한 값" }] } };
  assert.deepEqual(candidateConflict(withBusiness, candidate), { current: "직접 수정한 값", changed: true, requiresOverwrite: true });
  assert.equal(candidateConflict(withBusiness, { ...candidate, value: "직접 수정한 값" }).requiresOverwrite, false);
  assert.equal(candidateConflict(original, candidate).requiresOverwrite, true, "Deletion during extraction also requires consent");
  assert.equal(shouldAcceptSnapshot(original, { ...original, coach: { ...original.coach, revision: 1 } }), false);
  assert.equal(shouldAcceptSnapshot(original, { ...original, updatedAt: "2026-09-15T00:00:00.000Z" }), false);
  assert.equal(shouldAcceptSnapshot(original, { ...original, planId: "other" }), false);
  assert.equal(shouldAcceptSnapshot(original, { ...original, coach: { ...original.coach, revision: 3 } }), true);
  assert.equal(readIntakePayload({ flowVersion: 2, enabled: true, ownerScope: scope, code: "owner_changed" })?.code, "owner_changed");
  assert.equal(readIntakePayload({ flowVersion: 2, enabled: true, login: true })?.plan, null);
  assert.equal(readIntakePayload({ plan: original }), null);
  assert.equal(plainText("[처음 구상] 예약 관리"), "[처음 구상] 예약 관리");
  assert.equal(plainText('{"numbers":[1,2]}'), "");
  assert.ok(!readableFinancialSummary({ ...original, financialSummary: '{"internal":true}' }).includes("internal"));
  const money = { ...original, financialSummary: "", coach: { ...original.coach, fields: [{ key: "budget" as const, value: "100만원", basis: "user" as const, messageId: "budget", quote: "100만원" }] } };
  assert.match(readableFinancialSummary(money), /준비 예산: 1,000,000원/, "Stored amounts are thousands-formatted for display only");
  assert.match(readableFinancialSummary(money), /0원으로 계산하지/);

  // ---- Select-first controls (spec §2, §6 Phase 2) ----
  const startupQuestions = coreQuestions("startup");
  const exploringFixture = fixture("exploring");
  const candidateChoice = coreQuestions("exploring").find(question => question.id === "candidate")!;
  const customerBase = startupQuestions.find(question => question.id === "customer")!;
  const customerChips: IntakeQuestion = { ...customerBase, hint: "최대 2개까지 고를 수 있어요", options: [
    { value: "개인", label: "개인 소비자", group: "filter:고객 유형" }, { value: "사업자", label: "사업자", group: "filter:고객 유형" },
    { value: "점심 직장인", label: "점심·테이크아웃을 찾는 인근 직장인", group: "고객" }, { value: "가족", label: "주거 상권 가족·주부", group: "고객" }, { value: "학생", label: "대학가·학원가 학생", group: "고객" },
  ] };
  assert.equal(isHybridQuestion(customerChips), true);
  assert.equal(isHybridQuestion(customerBase), false, "text without options stays a plain composer question");
  assert.equal(isHybridQuestion({ id: "business", kind: "text", options: [{ value: "카페", label: "○○ 카페를 운영합니다" }] }), false, "business is the typing exception");
  assert.equal(isPrefillQuestion({ id: "business", kind: "text", options: [{ value: "카페", label: "○○ 카페를 운영합니다" }] }), true);
  let picks = toggleChip(customerChips, [], "개인");
  assert.deepEqual(picks, ["개인"]);
  assert.deepEqual(toggleChip(customerChips, picks, "사업자"), ["사업자"], "filter steps hold one pick");
  picks = toggleChip(customerChips, picks, "가족"); picks = toggleChip(customerChips, picks, "학생");
  assert.deepEqual(picks, ["개인", "가족", "학생"]);
  assert.deepEqual(toggleChip(customerChips, picks, "점심 직장인"), picks, "customer keeps at most 2 picks in a step");
  assert.equal(assembleHybridText(customerChips, picks), "주거 상권 가족·주부, 대학가·학원가 학생", "filter picks are never written into the answer");
  assert.equal(assembleHybridText(customerChips, ["개인", "가족"], ["마포구 아파트 단지"]), "주거 상권 가족·주부 / 마포구 아파트 단지");
  assert.deepEqual(unmatchedPieces(customerChips, "주거 상권 가족·주부 / 마포구 아파트 단지"), ["마포구 아파트 단지"]);
  for (const text of ["○○ 카페를 운영합니다", "커피·음료 —", "베이커리 / ", "고객, ", "납품:", ""]) assert.equal(unfinishedAnswerText(text), true, text);
  for (const text of ["베이커리·디저트 / 주문: 카운터, 배달앱", "동네 카페를 운영합니다"]) assert.equal(unfinishedAnswerText(text), false, text);
  const feedbackMulti: IntakeQuestion = { id: "education.feedback", label: "평가·피드백 방식", prompt: "피드백?", kind: "multi", options: ["과제 첨삭", "테스트·퀴즈", "별도 피드백 없음"].map(label => ({ value: label, label })) };
  assert.equal(hasExclusiveOptions(feedbackMulti), true);
  assert.equal(hasExclusiveOptions(exploringFixture.nextQuestion!), false);
  assert.deepEqual(toggleChip(feedbackMulti, ["과제 첨삭", "테스트·퀴즈"], "별도 피드백 없음"), ["별도 피드백 없음"], "an exclusive chip clears its step");
  assert.deepEqual(toggleChip(feedbackMulti, ["별도 피드백 없음"], "과제 첨삭"), ["과제 첨삭"], "any other pick clears the exclusive chip");
  // Lib conventions (intake-options.ts CHIP_GROUPS): channel "common"+"sector" is one 8-chip step, capacity people → period → unit + count, goal period → metric → amount / count.
  const channelChips: IntakeQuestion = { ...startupQuestions.find(question => question.id === "channel")!, options: sectorChipOptions("food_beverage", "channel", "startup") };
  assert.equal(optionGroups(channelChips.options).length, 1, "common and sector chips render as a single step");
  let channelPicks: string[] = [];
  for (const label of ["매장 방문", "인스타그램·SNS", "배달앱(배민·쿠팡이츠)", "지인·입소문"]) channelPicks = toggleChip(channelChips, channelPicks, label);
  assert.deepEqual(channelPicks, ["매장 방문", "인스타그램·SNS", "배달앱(배민·쿠팡이츠)"], "channel keeps 3 picks across common and sector chips");
  assert.equal(assembleHybridText(channelChips, channelPicks), "매장 방문, 인스타그램·SNS, 배달앱(배민·쿠팡이츠)");
  assert.equal(toggleChip({ id: "experience", kind: "text", options: sectorChipOptions(null, "experience") }, ["문서·사무·기획"], "요리·카페·베이킹").length, 2, "experience is multi-pick");
  const capacityChips: IntakeQuestion = { ...startupQuestions.find(question => question.id === "capacity")!, options: sectorChipOptions("food_beverage", "capacity", "startup") };
  const capacityGroups = optionGroups(capacityChips.options);
  assert.equal(capacityGroups.length, 3);
  assert.equal(stepVisible(capacityChips, capacityGroups, 1, []), false);
  assert.equal(stepVisible(capacityChips, capacityGroups, 1, ["대표자 혼자"]), true);
  const capacityPicks = withCount(["대표자 혼자", "하루", "건"], 20);
  assert.deepEqual(capacityPicks, ["대표자 혼자", "하루", "건", "#20"]);
  assert.equal(selectedCount(capacityPicks), 20);
  assert.equal(assembleHybridText(capacityChips, capacityPicks), "대표자 혼자 / 하루 20건");
  assert.equal(assembleHybridText(capacityChips, ["대표자 혼자", "하루", "건"]), "대표자 혼자 / 하루", "no count → no dangling unit");
  const capacitySeed = seedAnswerDraft(capacityChips, "대표자 혼자 / 하루 20건");
  assert.deepEqual(capacitySeed.selected.sort(), ["#20", "대표자 혼자", "건", "하루"].sort(), "the composed volume piece restores period, unit and count");
  assert.deepEqual(unmatchedPieces(capacityChips, "대표자 혼자 / 하루 20건"), [], "a composed piece is not a free supplement");
  const goalChips: IntakeQuestion = { ...startupQuestions.find(question => question.id === "goal")!, options: sectorChipOptions("food_beverage", "goal", "startup") };
  const goalGroups = optionGroups(goalChips.options);
  assert.equal(stepVisible(goalChips, goalGroups, 2, ["6개월 안에", "첫 유료 고객·첫 판매"]), false, "amount step only for N원 metrics");
  assert.equal(stepVisible(goalChips, goalGroups, 2, ["6개월 안에", "월 매출 N원"]), true);
  assert.equal(assembleHybridText(goalChips, ["6개월 안에"]), "", "a period alone is not a goal");
  assert.equal(assembleHybridText(goalChips, ["6개월 안에", "월 매출 N원"]), "6개월 안에 월 매출 N원");
  assert.equal(unfinishedAnswerText("6개월 안에 월 매출 N원"), true, "an unfilled N원 placeholder blocks the save");
  assert.equal(assembleHybridText(goalChips, ["6개월 안에", "월 매출 N원", "1,000만원"]), "6개월 안에 월 매출 1,000만원");
  assert.equal(assembleHybridText(goalChips, withCount(["기간 미정", "월 주문·계약 N건"], 30)), "월 주문·계약 30건", "기간 미정 saves the metric alone");
  const goalSeed = seedAnswerDraft(goalChips, "6개월 안에 월 매출 1,000만원");
  assert.deepEqual(goalSeed.selected, ["6개월 안에", "월 매출 N원", "1,000만원"]);
  assert.deepEqual(seedAnswerDraft(goalChips, "월 주문·계약 30건").selected, ["월 주문·계약 N건", "#30"]);
  assert.equal(CHIP_GROUPS.priceBasis, "basis");
  const hybridSeed = seedAnswerDraft(customerChips, "주거 상권 가족·주부 / 마포구 아파트 단지");
  assert.deepEqual([hybridSeed.selected, hybridSeed.text], [["가족"], "주거 상권 가족·주부 / 마포구 아파트 단지"], "exact label pieces restore chips; the sentence stays in the composer");
  const legacyMulti = seedAnswerDraft(feedbackMulti, "과제 첨삭과 상담으로 확인");
  assert.deepEqual([legacyMulti.selected, legacyMulti.text], [[], "과제 첨삭과 상담으로 확인"], "a legacy prose answer on a multi question lights no chip");
  assert.deepEqual(seedAnswerDraft(feedbackMulti, ["과제 첨삭", "예전 값"]).selected, ["과제 첨삭"]);
  assert.deepEqual(seedAnswerDraft(feedbackMulti, ["과제 첨삭", "예전 값"]).text, "예전 값");
  const budgetQuestion = startupQuestions.find(question => question.id === "budget")!;
  const hoursQuestion = startupQuestions.find(question => question.id === "hoursPerWeek")!;
  assert.equal(seedAnswerDraft(budgetQuestion, "12,000원").text, "12000");
  assert.equal(seedAnswerDraft(budgetQuestion, "300만원").text, "3000000");
  const proseAmount = seedAnswerDraft({ ...budgetQuestion, id: "price" }, "대표 메뉴 1개 7500");
  assert.deepEqual([proseAmount.text, proseAmount.hint], ["", "대표 메뉴 1개 7500"], "unparsable legacy amounts seed empty with the original as a hint");
  assert.equal(seedAnswerDraft(hoursQuestion, "10시간").text, "10");
  assert.equal(seedAnswerDraft(hoursQuestion, 10).text, "10");
  assert.equal(seedAnswerDraft(hoursQuestion, null).text, "");
  const periodQuestion = coreQuestions("operating").find(question => question.id === "period")!;
  assert.equal(seedAnswerDraft(periodQuestion, "2026-01-01 / 2026-06-30").text, "2026-01-01 / 2026-06-30");
  assert.deepEqual(seedAnswerDraft(candidateChoice, exploringFixture.candidateIdeas[0].id, exploringFixture.candidateIdeas).selected, [exploringFixture.candidateIdeas[0].id]);
  assert.equal(summaryAnswerText(hoursQuestion, "10시간"), "10시간 / 주");
  assert.equal(summaryAnswerText(budgetQuestion, "3000000원"), "3,000,000원");
  assert.equal(summaryAnswerText(detailQuestions("food_beverage").find(question => question.id === "food_beverage.peakOrders")!, 30), "30건 / 시간");
  assert.equal(summaryAnswerText(candidateChoice, exploringFixture.candidateIdeas[0].id, exploringFixture.candidateIdeas), exploringFixture.candidateIdeas[0].title);
  assert.equal(summaryAnswerText(exploringFixture.nextQuestion!, ["software"]), "소프트웨어 · 플랫폼");

  const require = createRequire(import.meta.url);
  const css = readFileSync(new URL("../app/plan/chat/intake.module.css", import.meta.url), "utf8");
  const cssClasses = Object.fromEntries([...css.matchAll(/\.([a-zA-Z][a-zA-Z0-9_-]*)/g)].map(match => [match[1], match[1]]));
  require.extensions[".css"] = module => { module.exports = cssClasses; };
  const { EntryChoices, QuestionForm, BusinessSummary, ConversationHistory, ExtractionReview, SavedNotes, AnswerHistory, ReplyTyping } = await import("../app/plan/chat/intake-ui/IntakePanels");
  const noop = () => {};
  const entry = renderToStaticMarkup(<EntryChoices disabled={false} onStart={noop} />);
  assert.equal((entry.match(/<button/g) ?? []).length, 3);
  for (const label of ["아이디어를 찾고 있어요", "생각한 사업이 있어요", "사업을 운영 중이에요"]) assert.ok(entry.includes(label));
  assert.ok(entry.includes("data-coach-welcome"), "The original chat welcome is reused");
  const firstMessage = renderToStaticMarkup(<EntryChoices initialMessage="먼저 적은 사업 이야기" disabled={false} onStart={noop} />);
  assert.ok(firstMessage.indexOf("먼저 적은 사업 이야기") < firstMessage.indexOf("대화 시작 선택지"), "Typed introduction precedes the stage choices inside the conversation");
  const form = (snapshot: IntakeSnapshot, question = snapshot.nextQuestion!, value = emptyAnswer(), disabled = false) => renderToStaticMarkup(<QuestionForm question={question} snapshot={snapshot} draft={value} editing={false} disabled={disabled} onChange={noop} onAnswer={noop} onCancel={noop} />);
  const sectorMarkup = form(original);
  for (const sector of intakeSectorOptions) assert.ok(sectorMarkup.includes(sector.label), sector.label);
  assert.ok(sectorMarkup.includes(original.nextQuestion!.prompt));
  assert.equal((sectorMarkup.match(/type="radio"/g) ?? []).length, intakeSectorOptions.length);
  const exploring = fixture("exploring");
  assert.equal((form(exploring).match(/type="checkbox"/g) ?? []).length, intakeSectorOptions.length);
  const candidateQuestion = coreQuestions("exploring").find(question => question.id === "candidate")!;
  const candidateMarkup = form(exploring, candidateQuestion);
  for (const idea of exploring.candidateIdeas) { assert.ok(candidateMarkup.includes(idea.title)); assert.ok(candidateMarkup.includes(idea.description)); }
  assert.ok(form(exploring, candidateQuestion, { ...emptyAnswer(), custom: true }).includes("<textarea"));
  const numericMarkup = form(original, coreQuestions("startup").find(question => question.id === "budget")!, { ...emptyAnswer(), text: "0" });
  assert.ok(numericMarkup.includes('inputMode="decimal"'));
  assert.ok(numericMarkup.includes("단위: 원"));
  const activeQuestion = coreQuestions("startup").find(question => question.id === "business")!;
  assert.ok(!form(active, activeQuestion, answer).includes("disabled="), "An active extraction job does not disable answer submission");
  const savingMarkup = form(active, activeQuestion, answer, true);
  assert.ok(savingMarkup.includes("disabled="));
  assert.ok(!savingMarkup.match(/<textarea[^>]*disabled/), "Network save can block commits, never typing");
  assert.ok(form(original, detailQuestions("software")[1]).includes("출시·제공 중"));
  const chatQuestion = renderToStaticMarkup(<QuestionForm inChat question={activeQuestion} snapshot={original} draft={emptyAnswer()} editing={false} disabled={false} onChange={noop} onAnswer={noop} onCancel={noop} />);
  assert.ok(chatQuestion.includes("data-chat-question"));
  assert.ok(!chatQuestion.includes("<textarea"), "The live question uses the persistent bottom composer rather than an inline survey field");
  assert.ok(!chatQuestion.includes("답변 저장"), "Submission lives in the bottom composer");
  assert.equal((chatQuestion.match(/<button/g) ?? []).length, 1, "The text question has one clear alternate action: unknown");
  assert.ok(chatQuestion.includes('class="unknownButton"'));
  assert.ok(!chatQuestion.includes("이전 답변 수정"));
  const chat = (question: IntakeQuestion, value = emptyAnswer(), snapshot = original) => renderToStaticMarkup(<QuestionForm inChat question={question} snapshot={snapshot} draft={value} editing={false} disabled={false} onChange={noop} onAnswer={noop} onCancel={noop} />);
  const buttonMarkup = (markup: string, label: string) => markup.match(new RegExp(`<button[^>]*>(?:(?!</button>).)*${label}`))?.[0] ?? "";
  const prefillOptions = ["○○ 카페를 운영합니다", "○○ 지역에서 ○○ 방문 서비스를 합니다", "○○를 온라인 판매(스마트스토어)합니다"];
  const prefillMarkup = chat({ ...activeQuestion, options: prefillOptions.map(label => ({ value: label, label })) });
  assert.equal((prefillMarkup.match(/<button/g) ?? []).length, 1 + prefillOptions.length, "business shows unknown + prefill chips; the composer stays the commit path");
  assert.ok(!prefillMarkup.includes("이대로 저장") && !prefillMarkup.includes("답변 저장"), "Prefill chips never save by themselves");
  for (const label of prefillOptions) assert.ok(prefillMarkup.includes(label));
  const hybridEmpty = chat(customerChips);
  assert.ok(hybridEmpty.includes("이대로 저장") && !hybridEmpty.includes("답변 저장"), "Inline commit is named differently from the composer button");
  assert.ok(hybridEmpty.includes("최대 2개까지 고를 수 있어요"), "question.hint renders under the prompt");
  assert.ok(hybridEmpty.includes("개인 소비자") && !hybridEmpty.includes("주거 상권 가족·주부"), "Later steps stay hidden until the first step has a pick");
  assert.ok(!hybridEmpty.includes("<textarea"));
  assert.match(buttonMarkup(hybridEmpty, "이대로 저장"), /disabled/);
  const hybridFilterOnly = chat(customerChips, { ...emptyAnswer(), selected: ["개인"] });
  assert.ok(hybridFilterOnly.includes("주거 상권 가족·주부"), "A filter pick reveals the next step");
  assert.match(buttonMarkup(hybridFilterOnly, "이대로 저장"), /disabled/, "A filter-only pick cannot be saved");
  assert.ok(hybridFilterOnly.includes("최대 2개 · 0/2"));
  const hybridReady = chat(customerChips, { text: "주거 상권 가족·주부", selected: ["개인", "가족"], custom: false });
  assert.doesNotMatch(buttonMarkup(hybridReady, "이대로 저장"), /disabled/);
  assert.match(buttonMarkup(hybridReady, "주거 상권 가족·주부"), /aria-pressed="true"/);
  assert.match(buttonMarkup(chat(customerChips, { text: "주거 상권 가족·주부 / ", selected: ["개인", "가족"], custom: false }), "이대로 저장"), /disabled/, "A dangling separator blocks the save");
  assert.equal((hybridReady.match(/<button/g) ?? []).length, 2 + 3 + 3, "filter 2 + step 3 + 이대로 저장·미정·직접 입력");
  const capacityChat = chat(capacityChips, { text: "대표자 혼자 / 하루", selected: ["대표자 혼자", "하루", "건"], custom: false });
  assert.ok(capacityChat.includes('aria-label="건 수량"') && capacityChat.includes("약 ") === false, "unit pick reveals the count step");
  for (const preset of numberPresets({ id: "capacity", unit: "건" })) assert.ok(capacityChat.includes(`${preset}건`), `capacity preset ${preset}`);
  assert.doesNotMatch(buttonMarkup(capacityChat, "이대로 저장"), /disabled/, "people alone is a saveable capacity answer");
  const spacePrice: IntakeQuestion = { ...startupQuestions.find(question => question.id === "price")!, kind: "number", unit: "원", period: "이용 1건", options: sectorChipOptions("space_hospitality", "price", "startup") };
  const spaceSnapshot = { ...original, intake: { ...original.intake, sector: "space_hospitality" as const } };
  const basisChat = chat(spacePrice, emptyAnswer(), spaceSnapshot);
  assert.ok(basisChat.includes("시간당") && basisChat.includes("1박") && !basisChat.includes('data-stage="ranges"'), "space price asks for a basis before its ladder");
  const basisPicked = chat(spacePrice, { ...emptyAnswer(), selected: ["1박"] }, spaceSnapshot);
  for (const range of amountRanges("space_hospitality", "price", "startup", "1박")) assert.ok(basisPicked.includes(range.label), range.label);
  const operatingProblem: IntakeQuestion = { ...coreQuestions("operating").find(question => question.id === "problem")!, options: sectorChipOptions("food_beverage", "problem", "operating") };
  const problemChat = chat(operatingProblem, emptyAnswer(), fixture("operating"));
  assert.equal((problemChat.match(/aria-pressed=/g) ?? []).length, 8, "operating problem shows common 6 + sector 2 in one grid");
  const interestChat = chat(exploring.nextQuestion!, emptyAnswer(), exploring);
  assert.ok(interestChat.includes("선택 완료(0개)") && /disabled/.test(buttonMarkup(interestChat, "선택 완료")), "multi has an inline commit that waits for a pick");
  assert.equal((interestChat.match(/type="checkbox"/g) ?? []).length, intakeSectorOptions.length);
  assert.doesNotMatch(buttonMarkup(chat(exploring.nextQuestion!, { ...emptyAnswer(), selected: ["software", "education"] }, exploring), "선택 완료"), /disabled/);
  assert.ok(chat(exploring.nextQuestion!, { ...emptyAnswer(), selected: ["software", "education"] }, exploring).includes("선택 완료(2개)"));
  const industryHints = chat({ ...original.nextQuestion!, options: original.nextQuestion!.options!.map(option => ({ ...option, hint: `${option.label} 예시` })) });
  assert.ok(industryHints.includes('class="optionHint"') && !industryHints.includes("optionDescription"), "Chip helper text uses its own small class so the grid keeps two columns");
  const hoursChat = chat(hoursQuestion, { ...emptyAnswer(), text: "10" });
  assert.ok(hoursChat.includes('aria-label="값 조정"') && hoursChat.includes("이 값으로 저장"), "number_quick renders a stepper");
  assert.ok(hoursChat.includes('aria-label="5시간 늘리기"'), "time-like units step by 5");
  for (const preset of numberPresets(hoursQuestion)) assert.ok(hoursChat.includes(`${preset.toLocaleString("ko-KR")}시간`), `preset ${preset}`);
  assert.ok(!hoursChat.includes("<textarea"));
  const budgetChat = chat(budgetQuestion);
  const budgetRanges = amountRanges(original.intake.sector, "budget", "startup");
  if (budgetRanges.length) { for (const range of budgetRanges) assert.ok(budgetChat.includes(range.label), range.label); assert.ok(budgetChat.includes('data-stage="ranges"')); }
  else assert.ok(budgetChat.includes("만원") && budgetChat.includes("이 금액으로 저장") && budgetChat.includes('data-stage="exact"'), "Without a ladder the 만원 keypad opens directly");
  assert.ok(!budgetChat.includes('inputMode="decimal" autoComplete="off" maxLength="80"'), "The chat number question uses the ladder or stepper, not the survey field");
  const hinted = chat(budgetQuestion, { ...emptyAnswer(), hint: "대표 메뉴 1개 7500" });
  assert.ok(hinted.includes("이전 답변: 대표 메뉴 1개 7500"));
  const periodChat = chat(periodQuestion, { ...emptyAnswer(), text: "2026-01-01 / 2026-06-30" }, fixture("operating"));
  for (const label of ["지난달", "최근 3개월", "최근 6개월", "최근 12개월", "올해", "작년", "직접 선택"]) assert.ok(periodChat.includes(label), label);
  assert.ok(periodChat.includes('value="2026-01-01"') && periodChat.includes('value="2026-06-30"'), "Editing a period seeds both date inputs");
  assert.equal((periodChat.match(/<button/g) ?? []).length, 6 + 1 + 1 + 1, "6 presets + 직접 선택 + 미정 + 이 기간으로 저장");
  const recommendedQuestion = renderToStaticMarkup(<QuestionForm inChat question={original.nextQuestion!} snapshot={suggestedBusiness} draft={emptyAnswer()} editing={false} disabled={false} onChange={noop} onAnswer={noop} onCancel={noop} />);
  for (const text of ["이 업종으로 정리할까요", "기업 서비스", "이 업종으로 계속", "직접 선택하기"]) assert.ok(recommendedQuestion.includes(text));
  assert.ok(!recommendedQuestion.includes('type="radio"'), "The long industry list is collapsed until explicitly opened");
  const industryEdit = renderToStaticMarkup(<QuestionForm inChat question={original.nextQuestion!} snapshot={suggestedBusiness} draft={{ ...emptyAnswer(), selected: ["education"] }} editing disabled={false} onChange={noop} onAnswer={noop} onCancel={noop} />);
  assert.ok(industryEdit.includes('type="radio"'));
  assert.ok(!industryEdit.includes("이 업종으로 계속"), "Existing industry edits are not replaced by the automatic recommendation");
  assert.ok(suggestedBusiness.ksicCandidates.length > 0, "KSIC candidates are derived from the confirmed business text without AI");
  assert.ok(recommendedQuestion.includes("표준산업분류 후보") && recommendedQuestion.includes(suggestedBusiness.ksicCandidates[0].name), "The industry step offers KSIC candidates as chips");
  assert.ok(!industryEdit.includes("표준산업분류 후보"), "Editing an existing industry shows the full list instead of candidates");
  assert.equal(original.ksicCandidates.length, 0, "No business text yet → no candidates");
  assert.ok(recommendedQuestion.includes("업종 이름으로 찾기"), "The industry step offers a name search field without leaving the chat");
  assert.ok(original.structure && original.structure.basis.revenue === "sector" && original.structure.values.sector === "general", "Without KSIC the structure falls back to the sector default");
  const typing = renderToStaticMarkup(<ReplyTyping />);
  assert.ok(typing.includes('role="status"'));
  assert.ok(typing.includes('aria-label="다음 질문 준비 중"'));
  assert.equal((typing.match(/<i>/g) ?? []).length, 3);
  const chatHistory = renderToStaticMarkup(<ConversationHistory snapshot={preview} onEdit={noop} />);
  assert.equal((chatHistory.match(/data-coach-message="user"/g) ?? []).length, 2);
  assert.ok(chatHistory.includes(original.nextQuestion!.prompt));
  assert.ok(chatHistory.includes("업종 답변 수정"));
  const review = renderToStaticMarkup(<ExtractionReview snapshot={{ ...withBusiness, intake: { ...withBusiness.intake, candidates: [candidate] } }} disabled={false} onCommand={noop} />);
  for (const text of ["현재 값", "직접 수정한 값", "추출한 새 값", "현재 값을 이 내용으로 바꾸기", "선택 제외", "선택 반영"]) assert.ok(review.includes(text));
  const summarized = previewIntakeAnswer(original, command())!;
  summarized.coreComplete = true; summarized.hasDocuments = true;
  summarized.coach.design = { status: "proposal", sourceRevision: 1, approach: "new-concept", startingPlan: { scope: "AI가 제안한 시작 범위", connectionToVision: "구상과의 관계", whyThis: "제안 이유", notIncluded: [] }, alternatives: [], assumptions: [], nextAction: { action: "다음 행동", doneWhen: "완료 기준", usableText: "사용할 문구" } };
  const summary = renderToStaticMarkup(<BusinessSummary onStructure={noop} snapshot={summarized} disabled aiBusy prepared={false} onEdit={noop} onDetails={noop} onDesign={noop} onPrepare={noop} />);
  for (const text of ["입력한 사업 요약", "소규모 매장의 예약 업무를 돕는 소프트웨어", "AI가 제안한 시작 범위", `상세 질문 ${structureQuestions(summarized.intake.mode, summarized.structure?.values).length + detailQuestions(summarized.intake.sector).length}개 추가`, "이 내용으로 사업안 만들기", "계획서 만들기"]) assert.ok(summary.includes(text));
  assert.ok(summary.includes(`/plan/document?planId=${id}`), "Existing artifacts stay navigable even during AI jobs");
  let numbered = previewIntakeAnswer(original, command({ questionId: "budget", value: "200만원" }))!;
  numbered = previewIntakeAnswer(numbered, { ...command({ questionId: "hoursPerWeek", value: "10시간" }), revision: numbered.coach.revision })!;
  assert.equal(numbered.coach.fields.find(field => field.key === "budget")?.value, "2000000원", "Storage keeps the raw coachAmount string");
  const numberedSummary = renderToStaticMarkup(<BusinessSummary onStructure={noop} snapshot={numbered} disabled={false} aiBusy={false} prepared={false} onEdit={noop} onDetails={noop} onDesign={noop} onPrepare={noop} />);
  assert.ok(numberedSummary.includes("2,000,000원"), "Summary formats amounts");
  assert.ok(numberedSummary.includes("10시간 / 주"), "Summary attaches unit and period");
  assert.ok(!summary.includes("AI 준비 완료"));
  const noteMarkup = renderToStaticMarkup(<SavedNotes snapshot={{ ...original, intake: { ...original.intake, notes: [{ id: "n", text: "사용자가 남긴 원문", at, status: "failed" }] } }} disabled={false} onExtract={noop} />);
  assert.ok(noteMarkup.includes("사용자가 남긴 원문"));
  assert.ok(noteMarkup.includes("메모 원문은 저장되어 있습니다"));
  const orphan = renderToStaticMarkup(<AnswerHistory snapshot={original} drafts={{ "food_beverage.signatureMenu": { ...emptyAnswer(), text: "업종 변경 전 입력한 대표 메뉴", label: "대표 메뉴" } }} onEdit={noop} onKeepAsMemo={noop} />);
  assert.ok(orphan.includes("업종 변경 전 입력한 대표 메뉴"));
  assert.ok(orphan.includes("자유 메모로 가져오기"));
  assert.match(css, /prefers-reduced-motion/);
  assert.match(css, /:focus-visible/);
  assert.match(css, /minmax\(0, 1fr\)/);
  assert.ok(!/letter-spacing:\s*-/.test(css));
  for (const selector of [".chip ", ".chipRow", ".stepper", ".stepButton", ".keypad ", ".unitToggle", ".optionHint", ".questionHint", ".draftHint"]) assert.ok(css.includes(selector), selector);
  assert.match(css.slice(css.lastIndexOf("@media (max-width: 400px)")), /\.chip\b/, "Narrow phones tighten the chips");
  const source = readFileSync(new URL("../app/plan/chat/BusinessIntake.tsx", import.meta.url), "utf8");
  assert.match(source, /"x-business-intake-owner": ownerScope.current/);
  assert.ok(!source.includes('action: "extract-pending"'), "The unified composer never auto-dispatches note extraction");
  assert.ok(!source.includes("MODE_LABELS"), "Input modes are not exposed as persistent tabs");
  assert.match(source, /routeComposerInput/);
  assert.match(source, /readChatResponse/);
  assert.match(source, /note.status === "queued"/);
  assert.match(source, /input && draftRef.current.pending/);
  assert.match(source, /replaceState\(null, "", target\)/, "Next's URL wrapper must receive non-internal history state");
  assert.match(source, /if \(stored && previousKey !== storageKey.current\)/, "Keep the old backup if plan-scoped storage fails");
  assert.match(source, /freezeForOwnerChange = useCallback\(\(\) => \{\s*routeEpoch.current \+= 1/);
  assert.ok(!source.includes("setInterval(() => void send"));
  assert.match(source, /enterKeyHint="send"/);
  assert.match(source, /!event.shiftKey && !event.nativeEvent.isComposing && event.nativeEvent.keyCode !== 229/);
  assert.ok(!source.includes('window.matchMedia("(min-width:901px)").matches'), "Sending with Enter must not depend on the viewport width");
  const conversationMarkup = source.slice(source.indexOf('<main ref={inputPane}'), source.indexOf('</main>'));
  assert.ok(!conversationMarkup.includes("<AnswerHistory"), "Answer history belongs in the summary, not below the next chat question");
  assert.match(source, /finishReply\(pending.command.requestId, saved\)/, "Failed saves must cancel question reveal");
  assert.match(source, /box.bottom - visibleAnswer/, "Auto-scroll preserves the last user answer, not just the next question");
  const transition = readFileSync(new URL("../app/plan/chat/intake-ui/use-reply-transition.ts", import.meta.url), "utf8");
  assert.match(transition, /prefers-reduced-motion: reduce/);
  assert.match(transition, /active.current\?\.requestId !== requestId/);
  assert.match(transition, /saved \? Math.max\(0, readyAt.current - performance.now\(\)\) : 0/);
  console.log(`business-intake-ui: ownership, pending retries, optimistic rollback inputs, select-first controls (hybrid chips, multi commit, number stepper, amount ladder, period presets, seeds), extraction consent, source summary, artifact links passed; local next-question p95 ${p95.toFixed(2)}ms`);
}

void main().catch(error => { console.error(error); process.exitCode = 1; });
