import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { seedBusinessRewriteFixture, mockRewrite, rewriteRequest, documentFixtureResult } from "./proposal-rewrite-fixture";
import { loadPlanState, savePlanState, preserveServerCoachRecords } from "../lib/plan-builder/plan-server-store";
import { saveBusinessConditions } from "../lib/plan-builder/coach-expert-service";
import { saveDocumentEdit } from "../lib/plan-builder/document-edit";
import { loadProposalEditor, updateSavedProposal } from "../lib/plan-builder/proposal-editor-service";
import { previewDocumentRefresh, runDocumentRefresh, reserveDocumentRefresh, executeDocumentRefresh, type DocumentRefreshRuntime } from "../lib/plan-builder/document-refresh-service";
import { previewProposalRewrite, runProposalRewrite } from "../lib/plan-builder/proposal-rewrite-service";
import { DOCUMENT_REFRESH_TIMEOUT_MS, type DocumentRefreshPreview } from "../lib/plan-builder/document-refresh";
import { readSavedProposal } from "../lib/plan-builder/proposal-editor";

const requestFor = (preview: DocumentRefreshPreview) => ({ type: "document_generate" as const, id: randomUUID(), hash: preview.hash, sections: preview.sections.map(section => section.key), consent: true as const });
async function main() {
  Object.assign(process.env, { PERSISTENCE_MODE: "demo-memory", SUPABASE_URL: "", SUPABASE_SERVICE_ROLE_KEY: "", OPENAI_API_KEY: "", ANTHROPIC_API_KEY: "" });
  let calls = 0;
  const runtime: DocumentRefreshRuntime = { target: { provider: "mock", model: "local-only" }, generate: async payload => { calls++; return documentFixtureResult(payload); } };
  const owner = randomUUID(), planId = "document-refresh", fixture = await seedBusinessRewriteFixture(owner, planId);
  await assert.rejects(() => previewDocumentRefresh(owner, planId, [fixture.commercialKey], runtime), /최신 조건/);
  await saveBusinessConditions(owner, { planId, requestId: randomUUID(), revision: 1, fields: [{ key: "price", value: "180만원" }] });
  const state = await loadPlanState(owner); state.plans[0].sections["overview/summary"].edited = true; state.plans[0].sections["market/personas"].locked = true; await savePlanState(owner, state);
  await assert.rejects(() => previewDocumentRefresh("other-owner", planId, [fixture.commercialKey], runtime), /찾을 수/);
  await assert.rejects(() => previewDocumentRefresh(owner, planId, [fixture.commercialKey, fixture.commercialKey], runtime), /서로 다른/);
  await assert.rejects(() => previewDocumentRefresh(owner, planId, fixture.keys.slice(0, 4), runtime), /최대 3개/);
  await assert.rejects(() => previewDocumentRefresh(owner, planId, ["not/in-plan"], runtime), /포함된/);
  await assert.rejects(() => previewDocumentRefresh(owner, planId, ["market/personas"], runtime), /잠긴 항목/);
  const keys = ["overview/summary", "market/products", fixture.commercialKey];
  const preview = await previewDocumentRefresh(owner, planId, keys, runtime), command = requestFor(preview);
  assert(!JSON.stringify(preview.payload).includes("messages")); assert(!JSON.stringify(preview.payload).includes("messageId"));
  assert.equal(preview.payload.sections.length, 3); assert(preview.payload.financialReference.includes("계획 시나리오"));
  await assert.rejects(() => runDocumentRefresh(owner, planId, { ...command, consent: false } as any, runtime), /요청/);
  await assert.rejects(() => runDocumentRefresh(owner, planId, { ...command, hash: "a".repeat(64) }, runtime), /다시 확인/);
  await assert.rejects(() => runDocumentRefresh(owner, planId, command, null), /아직 열지/);
  const before = structuredClone((await loadPlanState(owner)).plans[0].sections);
  const ready = await runDocumentRefresh(owner, planId, command, runtime);
  assert.equal(ready.documentRefresh?.status, "ready"); assert.equal(calls, 1);
  assert.deepEqual((await loadPlanState(owner)).plans[0].sections, before, "Draft generation cannot replace source documents");
  await runDocumentRefresh(owner, planId, command, runtime); assert.equal(calls, 1);
  await assert.rejects(() => runDocumentRefresh(owner, planId, { ...command, sections: [fixture.keys[1]] }, runtime), /같은 요청/);
  await assert.rejects(() => runDocumentRefresh(owner, planId, { type: "document_apply", id: command.id, expectedRevision: ready.revision, decisions: {} }), /각 문서 항목/);
  const decisions = Object.fromEntries(keys.map(key => [key, key === fixture.commercialKey ? "replace" as const : "keep" as const]));
  const apply = { type: "document_apply" as const, id: command.id, expectedRevision: ready.revision, decisions };
  const applied = await runDocumentRefresh(owner, planId, apply);
  assert.equal((await runDocumentRefresh(owner, planId, apply)).revision, applied.revision);
  assert.equal((await loadProposalEditor(owner, planId)).business?.documents.current, 3);
  assert.deepEqual(applied.document.deck, ready.document.deck, "Document approval does not silently change PPT");
  const latest = (await loadPlanState(owner)).plans[0];
  assert(latest.sections[fixture.commercialKey].markdown.includes("180만원")); assert(latest.sections[fixture.commercialKey].previous?.markdown.includes("150만원"));
  assert.equal(latest.sections["overview/summary"].markdown, before["overview/summary"].markdown);
  const locked = latest.sections["market/personas"];
  await saveDocumentEdit(owner, { planId, key: "market/personas", action: "review", baseGeneratedAt: locked.generatedAt, sourceRevision: 2 });
  let remaining = fixture.keys.filter(key => !keys.includes(key) && key !== "market/personas");
  while (remaining.length) {
    const batch = remaining.slice(0, 3); remaining = remaining.slice(3);
    const p = await previewDocumentRefresh(owner, planId, batch, runtime), r = requestFor(p);
    const draft = await runDocumentRefresh(owner, planId, r, runtime);
    await runDocumentRefresh(owner, planId, { type: "document_apply", id: r.id, expectedRevision: draft.revision, decisions: Object.fromEntries(batch.map(key => [key, "replace" as const])) });
  }
  assert.equal((await loadProposalEditor(owner, planId)).business?.documents.current, 9);
  const pptRuntime = { target: runtime.target, generate: async (payload: Parameters<typeof mockRewrite>[0]) => ({ result: mockRewrite(payload) }) };
  const pp = await previewProposalRewrite(owner, planId, pptRuntime); assert.equal(pp.impact.affected.length, 3);
  const pr = rewriteRequest(pp), pd = await runProposalRewrite(owner, planId, pr, pptRuntime);
  await runProposalRewrite(owner, planId, { type: "apply", id: pr.id, expectedRevision: pd.revision, choices: {} });
  assert.equal((await loadProposalEditor(owner, planId)).sourceChanged, false);

  const raceOwner = randomUUID(), raceId = "document-race";
  await seedBusinessRewriteFixture(raceOwner, raceId);
  await saveBusinessConditions(raceOwner, { planId: raceId, revision: 1, requestId: randomUUID(), fields: [{ key: "price", value: "180만원" }] });
  const p = await previewDocumentRefresh(raceOwner, raceId, [fixture.commercialKey], runtime), r = requestFor(p);
  let finish!: () => void, claimedCalls = 0;
  const slow: DocumentRefreshRuntime = { target: runtime.target, generate: payload => { claimedCalls++; return new Promise(resolve => { finish = () => resolve(documentFixtureResult(payload)); }); } };
  await reserveDocumentRefresh(raceOwner, raceId, r, slow);
  const working = executeDocumentRefresh(raceOwner, raceId, r.id, slow);
  while (!finish) await new Promise(resolve => setTimeout(resolve, 5));
  await executeDocumentRefresh(raceOwner, raceId, r.id, slow); assert.equal(claimedCalls, 1);
  await saveBusinessConditions(raceOwner, { planId: raceId, revision: 2, requestId: randomUUID(), fields: [{ key: "price", value: "200만원" }] });
  finish(); assert.equal((await working).documentRefresh?.error, "source_changed");
  const fresh = await previewDocumentRefresh(raceOwner, raceId, [fixture.commercialKey], runtime), retry = requestFor(fresh);
  const bad = await runDocumentRefresh(raceOwner, raceId, retry, { ...runtime, generate: async () => ({ sections: [{ key: "foreign/key", markdown: "bad", summary: "bad" }] }) });
  assert.equal(bad.documentRefresh?.error, "invalid_response");
  const cancelRequest = requestFor(await previewDocumentRefresh(raceOwner, raceId, [fixture.commercialKey], runtime));
  const cancelling = runDocumentRefresh(raceOwner, raceId, cancelRequest, slow);
  const oldFinish = finish;
  while (finish === oldFinish) await new Promise(resolve => setTimeout(resolve, 5));
  await runDocumentRefresh(raceOwner, raceId, { type: "document_dismiss", id: cancelRequest.id }); finish();
  assert.equal((await cancelling).documentRefresh?.status, "dismissed");
  const stored = await loadPlanState(raceOwner), forged = structuredClone(stored);
  delete forged.plans[0].answers.__proposal_editor;
  assert.deepEqual(readSavedProposal(preserveServerCoachRecords(forged, stored).plans[0].answers)?.documentRefresh, readSavedProposal(stored.plans[0].answers)?.documentRefresh);

  const reviewOwner = randomUUID(), reviewId = "document-review-race";
  await seedBusinessRewriteFixture(reviewOwner, reviewId);
  await saveBusinessConditions(reviewOwner, { planId: reviewId, revision: 1, requestId: randomUUID(), fields: [{ key: "price", value: "180만원" }] });
  const reviewKeys = [fixture.commercialKey, "market/products"];
  const reviewRequest = requestFor(await previewDocumentRefresh(reviewOwner, reviewId, reviewKeys, runtime));
  const reviewDraft = await runDocumentRefresh(reviewOwner, reviewId, reviewRequest, runtime);
  const originalSection = (await loadPlanState(reviewOwner)).plans[0].sections[fixture.commercialKey];
  await saveDocumentEdit(reviewOwner, { planId: reviewId, key: fixture.commercialKey, action: "save", baseGeneratedAt: originalSection.generatedAt, markdown: "다른 탭에서 확인한 최신 계약 조건", html: "<p>다른 탭에서 확인한 최신 계약 조건</p>" });
  const changedSections = structuredClone((await loadPlanState(reviewOwner)).plans[0].sections);
  await assert.rejects(() => runDocumentRefresh(reviewOwner, reviewId, { type: "document_apply", id: reviewRequest.id, expectedRevision: reviewDraft.revision, decisions: Object.fromEntries(reviewKeys.map(key => [key, "replace" as const])) }), /조건이나 문서가 바뀌/);
  assert.deepEqual((await loadPlanState(reviewOwner)).plans[0].sections, changedSections, "One changed source blocks the whole batch without overwriting either section");
  await runDocumentRefresh(reviewOwner, reviewId, { type: "document_dismiss", id: reviewRequest.id });

  const targetRequest = requestFor(await previewDocumentRefresh(reviewOwner, reviewId, [fixture.commercialKey], runtime));
  await reserveDocumentRefresh(reviewOwner, reviewId, targetRequest, runtime);
  const callsBeforeTarget = calls;
  const targetChanged = await executeDocumentRefresh(reviewOwner, reviewId, targetRequest.id, { ...runtime, target: { ...runtime.target, model: "different-model" } });
  assert.equal(targetChanged.documentRefresh?.error, "target_changed"); assert.equal(calls, callsBeforeTarget);

  const timeoutRequest = requestFor(await previewDocumentRefresh(reviewOwner, reviewId, [fixture.commercialKey], runtime));
  await reserveDocumentRefresh(reviewOwner, reviewId, timeoutRequest, runtime);
  await updateSavedProposal(reviewOwner, reviewId, saved => { saved.documentRefresh!.startedAt = new Date(Date.now() - DOCUMENT_REFRESH_TIMEOUT_MS - 1000).toISOString(); return saved; });
  assert.equal((await executeDocumentRefresh(reviewOwner, reviewId, timeoutRequest.id, runtime)).documentRefresh?.error, "timeout");
  assert.equal(calls, callsBeforeTarget, "Expired and retargeted jobs never invoke the generator");

  await updateSavedProposal(reviewOwner, reviewId, (saved, _state, plan) => { const section = plan.sections["market/products"]; plan.sections["market/products"] = { ...section, markdown: "", html: "", generatedAt: new Date(Date.parse(section.generatedAt) + 1).toISOString() }; return saved; });
  const emptyRequest = requestFor(await previewDocumentRefresh(reviewOwner, reviewId, ["market/products"], runtime));
  const emptyDraft = await runDocumentRefresh(reviewOwner, reviewId, emptyRequest, { ...runtime, generate: async () => ({ sections: [{ key: "market/products", markdown: "새로 작성한 상품 소개", summary: "상품 소개를 작성했습니다" }] }) });
  await assert.rejects(() => runDocumentRefresh(reviewOwner, reviewId, { type: "document_apply", id: emptyRequest.id, expectedRevision: emptyDraft.revision, decisions: { "market/products": "keep" } }), /기존 본문이 없는/);
  assert.equal((await loadPlanState(reviewOwner)).plans[0].sections["market/products"].markdown, "");
  console.log("document refresh: 3-item batches, consent/data bounds, immutable drafts, locked/manual protection, atomic review, old-source restore, chained PPT update, ownership, duplicate worker, changed source before/after generation, changed target, timeout, empty source, invalid output and late cancellation passed (mock only)");
}
void main().catch(error => { console.error(error); process.exitCode = 1; });
