import assert from "node:assert/strict";
import { createHash, randomUUID } from "node:crypto";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import JSZip from "jszip";
import { INDUSTRY_AI_FIXTURES } from "./industry-ai-fixtures";

assert.equal(process.argv.length, 2, "This reviewed offline export has no live mode");
Object.assign(process.env, { PERSISTENCE_MODE: "demo-memory", SUPABASE_URL: "", NEXT_PUBLIC_SUPABASE_URL: "", SUPABASE_SERVICE_ROLE_KEY: "", SUPABASE_ANON_KEY: "", OPENAI_API_KEY: "", ANTHROPIC_API_KEY: "", PROPOSAL_AI_ENABLED: "false", PAYMENTS_ENABLED: "false" });
globalThis.fetch = async () => { throw new Error("OFFLINE_EXPORT_ONLY"); };
const root = fileURLToPath(new URL("..", import.meta.url)), directory = join(root, "artifacts/industry-ai-20260915/b2b_service");
const checkpointPath = join(directory, "checkpoint.json"), ledgerPath = join(root, "artifacts/synthetic-ai-launch/budget.json");
const digest = (value: string | Uint8Array) => createHash("sha256").update(value).digest("hex");
const original = await readFile(checkpointPath, "utf8"), ledger = await readFile(ledgerPath, "utf8");
assert.equal(digest(original), "a1de22f4e8be807d901a41faf3bc1a0419c71b635af2d44930eb4e0526b0c103");
assert.equal(digest(ledger), "bee172213b51e76710b1f079b529bd150c124243ebf73110798a043c2fac57d1");
const checkpoint = JSON.parse(original);
assert.equal(checkpoint.status, "failed"); assert.equal(checkpoint.requestCount, 12);
assert(checkpoint.error.startsWith("JSON restore must preserve actual results"));
assert.equal(checkpoint.phases["restore-and-render"].status, "failed");
assert(Object.entries(checkpoint.phases).filter(([name]) => name !== "restore-and-render").every(([, phase]: [string, any]) => phase.status === "complete"));
assert.equal(Object.keys(checkpoint.phases).length, 9); assert(checkpoint.initialDeckGeneratedByAI);
const audit = join(directory, "offline-export-recovery"); await mkdir(audit, { mode: 0o700 });
await writeFile(join(audit, "original-checkpoint.json"), original, { flag: "wx", mode: 0o444 });
await writeFile(join(audit, "original-ledger.json"), ledger, { flag: "wx", mode: 0o444 });
const { normalizeState, loadPlanState, savePlanState } = await import("../lib/plan-builder/plan-server-store");
const { loadProposalEditor } = await import("../lib/plan-builder/proposal-editor-service");
const { readSavedProposal } = await import("../lib/plan-builder/proposal-editor");
const { renderableProposal } = await import("../lib/plan-builder/proposal-revision");
const { renderDeckPptx } = await import("../lib/plan-builder/deck-render");
const { pickDeckTheme } = await import("../lib/plan-builder/deck-themes");
const { renderPdf, renderDocx } = await import("../lib/delivery/document-renderer");
const { chaptersForType } = await import("../lib/plan-builder/blueprint");
const owner = `qa-offline-reconnected-${randomUUID()}`;
await savePlanState(owner, normalizeState(JSON.parse(JSON.stringify(checkpoint.state))));
const loaded = await loadPlanState(owner);
assert.deepEqual(loaded, checkpoint.state, "Every serialized business, document and PPT value survives reconnect");
const plan = loaded.plans[0], fixture = INDUSTRY_AI_FIXTURES[0], editor = await loadProposalEditor(owner, plan.id);
assert(editor.saved); assert.equal(editor.sourceChanged, checkpoint.expectedSourceChanged);
const persisted = readSavedProposal(plan.answers); assert(persisted);
assert.deepEqual(editor.saved.document.edits, persisted.document.edits);
const deck = renderableProposal(editor.saved.document);
const pptx = await renderDeckPptx(deck, pickDeckTheme("일반 사업계획서", fixture.name, loaded.business.description));
const zip = await JSZip.loadAsync(pptx, { checkCRC32: true }); assert(zip.file("ppt/presentation.xml"));
const slides = zip.file(/^ppt\/slides\/slide\d+\.xml$/), xml = (await Promise.all(slides.map(slide => slide.async("string")))).join("\n");
assert(xml.includes(`${fixture.name} 검토안`), "Manual title remains an editable PPTX object");
const entries = chaptersForType("일반 사업계획서").flatMap(chapter => chapter.sections.map(section => ({ key: `${chapter.id}/${section.id}`, title: section.title })));
const keys = ["overview/summary", "market/products", "strategy/price"];
const document = { id: plan.id, title: `${fixture.name} 검증용 요약 계획서`, type: "실제 AI 생성 3항목", versionLabel: "가상 검증", markdown: keys.map(key => `## ${entries.find(entry => entry.key === key)!.title}\n\n${plan.sections[key].markdown}`).join("\n\n") };
const project = { title: fixture.name, sector: fixture.sector, model: "가상 검증", customer: fixture.customer, generatedAt: new Date().toISOString(), sample: true };
const font = await readFile(join(root, "public/fonts/NanumGothic-Regular.ttf")), pdf = await renderPdf([document], project, font), docx = await renderDocx([document], project, font);
const outputs: Record<string, string> = {};
for (const [name, bytes] of [["updated.pptx", pptx], ["document.pdf", pdf], ["document.docx", docx]] as const) { await writeFile(join(directory, name), bytes, { mode: 0o600, flag: "wx" }); outputs[name] = digest(bytes); }
assert.equal(await readFile(ledgerPath, "utf8"), ledger, "Offline export cannot change the budget");
const at = new Date().toISOString();
const report = { status: "actual-ai-chain-complete-not-release-approved", synthetic: true, documentSections: 3, slides: deck.slides.length, outputs, initialDeckGeneratedByAI: true, templateGeneratedResultsReused: false, restore: "fresh isolated memory owner from exact saved JSON", paidCallsDuringExport: 0, sourceChanged: editor.sourceChanged, remainingGates: ["rendered page visual inspection", "full detailed plan", "11 sectors", "actual browser account reconnect", "remote Workflow/auth/PG", "PowerPoint/Google Slides", "human usability"] };
await writeFile(join(directory, "result.json"), JSON.stringify(report, null, 2), { mode: 0o600, flag: "wx" });
await writeFile(join(audit, "receipt.json"), JSON.stringify({ at, reason: "Undefined object properties are omitted by JSON; all serialized values must match", originalCheckpointSha256: digest(original), ledgerSha256: digest(ledger), preservedStateSha256: digest(JSON.stringify(checkpoint.state)), outputs, paidCalls: 0 }, null, 2), { mode: 0o444, flag: "wx" });
checkpoint.status = "complete"; delete checkpoint.error; checkpoint.outputHashes = outputs;
checkpoint.phases["restore-and-render"] = { ...checkpoint.phases["restore-and-render"], status: "complete", finishedAt: at, error: undefined, provenance: "reviewed-offline-JSON-restore-and-production-exports" };
await writeFile(`${checkpointPath}.tmp`, JSON.stringify(checkpoint, null, 2), { mode: 0o600 }); await rename(`${checkpointPath}.tmp`, checkpointPath);
console.log(JSON.stringify({ ...report, directory }, null, 2));
