import type { ProposalSector } from "../lib/plan-builder/proposal-blueprint";

export type IndustryAiFixture = { sector: ProposalSector; name: string; customer: string; offer: string; process: string; exclusions: string; price: string; nextPrice: string; unit: string; nextAction: string };
export const INDUSTRY_AI_FIXTURES: IndustryAiFixture[] = [
  { sector: "b2b_service", name: "QA 온결 제품소개", customer: "제품 설명 자료가 필요한 지역 제조사 영업 담당자", offer: "제품 소개서와 편집 원본 제작", process: "원본 자료 접수 후 초안을 검토하고 일괄 수정한 뒤 원본을 인계", exclusions: "번역과 촬영은 제외하며 실제 계약과 납품 이력 없음", price: "150만원", nextPrice: "180만원", unit: "프로젝트", nextAction: "가상 제품 자료로 납품 범위와 검수 기준을 확인" },
  { sector: "software", name: "QA 작은 업무판", customer: "요청을 메신저로 받는 소규모 디자인 팀", offer: "의뢰 등록과 진행 상태 확인용 웹 도구", process: "테스트 작업을 등록하고 담당자와 상태를 정한 뒤 완료 기록을 확인", exclusions: "결제와 외부 메신저 연동은 미구현이며 실제 사용자나 사용 로그 없음", price: "5만원", nextPrice: "6만원", unit: "팀당 월 구독", nextAction: "가상 요청으로 등록부터 완료까지 사용 흐름을 검증" },
  { sector: "food_beverage", name: "QA 새벽 컵", customer: "출근길에 음료를 가져가는 직장인", offer: "테이크아웃 커피 단일 메뉴", process: "재료 준비 후 주문을 받고 제조한 음료를 픽업대에서 전달", exclusions: "실제 매장과 메뉴 사진 및 판매 기록 없음", price: "5천원", nextPrice: "6천원", unit: "커피 한 잔", nextAction: "가상 주문으로 제조 동선과 대기 과정을 점검" },
  { sector: "retail_commerce", name: "QA 정리 상점", customer: "책상 소품을 정리하려는 재택근무자", offer: "케이블 정리 파우치 단일 상품", process: "상품 상태 확인 후 주문을 포장하고 발송 상태 및 교환 문의를 기록", exclusions: "실제 상품 이미지와 주문 실적 없음 배송비와 반품 비용 미확인", price: "2만원", nextPrice: "2만5천원", unit: "파우치 한 개", nextAction: "견본 포장과 교환 접수 기준을 확인" },
  { sector: "manufacturing", name: "QA 작은 지그", customer: "소형 부품 조립 작업을 하는 공방", offer: "작업 고정용 지그 시제품", process: "사용 치수를 확인하고 시제품을 제작한 뒤 고정 상태를 시험", exclusions: "양산과 인증 완료를 주장하지 않으며 시험 성적서와 납품 기록 없음", price: "3만원", nextPrice: "4만원", unit: "시제품 한 개", nextAction: "가상 규격에 맞춰 시험 항목과 합격 기준을 작성" },
  { sector: "education", name: "QA 첫 보고서", customer: "업무 보고서 작성이 익숙하지 않은 신입 담당자", offer: "보고서 구성 실습과 과제 피드백 과정", process: "가상 업무 상황으로 초안을 작성하고 피드백 후 수정본을 비교", exclusions: "취업이나 성과 향상을 보장하지 않으며 실제 수강생 기록 없음", price: "12만원", nextPrice: "15만원", unit: "과정 수강", nextAction: "견본 과제와 평가 기준을 만들고 강의 분량을 점검" },
  { sector: "local_service", name: "QA 생활 정리", customer: "주방 수납 정리를 요청하는 지역 거주자", offer: "주방 수납 분류와 배치 정리 서비스", process: "정리 대상과 방문 범위를 합의하고 분류 후 배치 결과를 확인", exclusions: "폐기물 운반과 청소는 제외하며 실제 방문 실적 없음", price: "6만원", nextPrice: "7만원", unit: "방문 작업", nextAction: "가상 상담으로 제외 작업과 완료 확인 기준을 점검" },
  { sector: "space_hospitality", name: "QA 조용한 회의실", customer: "외부 회의 공간이 필요한 소규모 팀", offer: "회의용 공간 시간제 대여안", process: "사용 목적을 확인하고 입실과 시설 점검 후 퇴실 상태를 확인", exclusions: "실제 공간 사진과 예약 이력 없음 숙박 제공 계획 없음", price: "8만원", nextPrice: "9만원", unit: "대여 세션", nextAction: "가상 도면으로 이용 범위와 시설 확인표를 정리" },
  { sector: "logistics", name: "QA 근거리 발송", customer: "지역 내 소량 상품을 발송하는 소형 판매자", offer: "근거리 소형 포장물 집하와 전달안", process: "발송 정보를 받고 포장 상태를 확인한 뒤 전달 결과와 예외를 기록", exclusions: "실제 처리 물량과 정시 배송률 없음 위험물과 냉장품 제외", price: "4천원", nextPrice: "5천원", unit: "포장물 한 건", nextAction: "가상 주소로 집하 가능 범위와 전달 실패 대응을 정리" },
  { sector: "content_media", name: "QA 브랜드 한 장면", customer: "상품 안내 영상을 준비하는 소형 브랜드", offer: "제공된 자료로 짧은 상품 소개 영상 편집", process: "자료 사용 권리를 확인하고 초안 편집 후 수정과 최종 파일 납품", exclusions: "촬영과 음원 구매는 제외하며 허가된 포트폴리오와 실제 성과 없음", price: "20만원", nextPrice: "25만원", unit: "영상 한 편", nextAction: "가상 원본으로 편집 범위와 사용 권리 확인표를 작성" },
  { sector: "general", name: "QA 아이디어 확인실", customer: "제공하려는 상품을 아직 정하지 못한 예비 운영자", offer: "선택한 구상을 간단한 종이 견본으로 정리하는 실험안", process: "가설과 필요한 자원을 정리하고 견본을 만든 뒤 확인 질문을 기록", exclusions: "업종과 수요가 아직 미정이며 사업성 검증과 판매 실적 없음", price: "3만원", nextPrice: "3만5천원", unit: "견본 정리 의뢰", nextAction: "가상 구상으로 제공 범위와 중단 기준을 정리" },
];
