import assert from "node:assert/strict";
import { mergeEditorAsyncPatch, type EditorOverrides, type EditorAsyncPatch } from "../lib/landing/editor-async";
import { issueUploadCleanupToken, readUploadCleanupToken, containsUploadReference } from "../lib/landing/upload-cleanup";
import { readEditorRecovery } from "../lib/landing/editor-recovery";

const base: EditorOverrides = { texts: { title: "기존 제목", price: "100만원" }, images: { hero: "old.jpg" }, links: {}, sizes: {}, hidden: [], order: [] };
const patch: EditorAsyncPatch = { session: 1, kind: "texts", before: { ...base.texts }, changes: { title: "새 제목", price: "180만원" } };
const changed = { ...base, texts: { ...base.texts, title: "직접 고친 제목", note: "별도 수정" }, images: { hero: "new.jpg" }, order: ["b", "a"] };
const result = mergeEditorAsyncPatch(changed, 1, patch);
assert.equal(result.state.texts.title, "직접 고친 제목");
assert.equal(result.state.texts.price, "180만원");
assert.equal(result.state.texts.note, "별도 수정");
assert.equal(result.state.images.hero, "new.jpg");
assert.deepEqual(result.state.order, ["b", "a"]);
assert.deepEqual(result.conflicts, ["title"]);
assert.equal(mergeEditorAsyncPatch(changed, 2, patch).state, changed);
assert.equal(mergeEditorAsyncPatch(changed, 2, patch).stale, true);
const image = mergeEditorAsyncPatch(changed, 1, { session: 1, kind: "images", before: base.images, changes: { hero: "upload.jpg" } });
assert.deepEqual(image.conflicts, ["hero"]);
assert.equal(image.state, changed);
assert.deepEqual(mergeEditorAsyncPatch(base, 1, { ...patch, versions: {} }, { "texts:title": 2 }).conflicts, ["title"]);
assert.equal(base.texts.price, "100만원");
const user = "12345678-1234-1234-1234-123456789012", path = `${user}/87654321-4321-4321-4321-210987654321.png`;
const token = issueUploadCleanupToken(path, user, "test-only", 1000);
assert.equal(readUploadCleanupToken(token, user, "test-only", 1001), path);
assert.equal(readUploadCleanupToken(token, "other-user", "test-only", 1001), null);
assert.equal(readUploadCleanupToken(token, user, "wrong-secret", 1001), null);
assert.equal(readUploadCleanupToken(`${token}x`, user, "test-only", 1001), null);
assert.equal(readUploadCleanupToken(token, user, "test-only", 3_601_001), null);
assert.equal(readUploadCleanupToken(token, user, "test-only", 999), null);
assert.throws(() => issueUploadCleanupToken(`${user}/../another.png`, user, "test-only"));
assert(containsUploadReference({ versions: [{ config: { image: "https://example.invalid/a.png" } }] }, "https://example.invalid/a.png"));
assert(!containsUploadReference({ image: "https://example.invalid/b.png" }, "https://example.invalid/a.png"));
const recovery = { version: 1, base: "base", savedAt: 1000, draft: { root: {}, content: [], brainwave: { page: "1-1", ...base } } };
assert.equal(readEditorRecovery(JSON.stringify(recovery), 1001)?.draft.brainwave?.texts.title, "기존 제목");
assert.equal(readEditorRecovery(JSON.stringify(recovery), 86_401_001), null);
assert.equal(readEditorRecovery("{bad"), null);
assert.equal(readEditorRecovery(JSON.stringify({ ...recovery, draft: {} })), null);
console.log("landing editor async: selective merge, element conflicts, session invalidation, cleanup ownership/signature/expiry, saved-reference guard and recovery validation passed");
