import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { completeJson, streamText, type LLMCompleteParams, type LLMConfig } from "../lib/llm/complete";
import { resolveIntakeLLMConfig } from "../lib/llm/intake-policy";
import { saveIntakeCommand, executeIntakeJob } from "../lib/plan-builder/intake-service";
import { loadPlanState } from "../lib/plan-builder/plan-server-store";
import { readIntake } from "../lib/plan-builder/intake-core";
import { readCoach } from "../lib/plan-builder/coach";

Object.assign(process.env,{PERSISTENCE_MODE:"demo-memory",RATE_LIMIT_BACKEND:"memory",SUPABASE_URL:"",SUPABASE_SERVICE_ROLE_KEY:"",OPENAI_API_KEY:"synthetic-only",ANTHROPIC_API_KEY:"synthetic-only",PLANNING_MODEL:"mock-primary",ANTHROPIC_MODEL:"mock-backup"});
const config:LLMConfig={provider:"openai",apiKey:"synthetic-only",model:"mock-primary"};
const alternate:LLMConfig={provider:"anthropic",apiKey:"synthetic-only",model:"mock-backup"};
const base:LLMCompleteParams={system:"Preserve contract",user:"카페 제외 / 주당 5시간 / 이전 후보 거절 이유",kind:"intake-help",maxOutputTokens:1200,jsonSchema:{name:"fixture",schema:{type:"object",properties:{message:{type:"string"}},required:["message"],additionalProperties:false}},validateJson:v=>typeof v.message==="string"};
const failover=():NonNullable<LLMCompleteParams["failover"]>=>({alternate,allowedErrors:["unavailable","rate_limited","timeout"],totalTimeoutMs:1000,attemptTimeoutMs:400,minRemainingMs:5,compatible:true,reserve:async()=>true});
const ok=(provider:string,value:unknown={message:"합성 응답"})=>Response.json(provider==="openai"?{status:"completed",output_text:JSON.stringify(value),usage:{input_tokens:10,output_tokens:5}}:{stop_reason:"end_turn",content:[{type:"text",text:JSON.stringify(value)}],usage:{input_tokens:10,output_tokens:5}});
const error=(status=503,type="server_error",message="Synthetic transient failure")=>Response.json({error:{type,message}},{status});
let failures=0,calls=0;
const check=async(name:string,run:()=>Promise<void>)=>{calls=0;try{await run();console.log("PASS "+name);}catch(e){failures++;console.error("FAIL "+name,e);}};
async function main(){
 await check("primary success: one reservation, no alternate, accepted usage once",async()=>{let reserved=0,usage=0,attemptUsage=0;globalThis.fetch=async()=>{calls++;return ok("openai");};assert(await completeJson(config,{...base,failover:{...failover(),reserve:async()=>{reserved++;return true;}},onUsage:()=>usage++,onAttemptUsage:()=>attemptUsage++}));assert.equal(calls,1);assert.equal(reserved,1);assert.equal(usage,1);assert.equal(attemptUsage,1);});
 await check("transient switches once with identical context and schema",async()=>{const bodies:Record<string,any>[]=[];globalThis.fetch=async(_u,init)=>{bodies.push(JSON.parse(String(init?.body)));calls++;return calls===1?error():ok("anthropic");};assert(await completeJson(config,{...base,failover:failover()}));assert.equal(calls,2);assert.equal(bodies[0].input[1].content,bodies[1].messages[0].content);assert(bodies[1].system.includes(base.system));assert(bodies[1].system.includes(JSON.stringify(base.jsonSchema!.schema)));});
 for(const provider of ["openai","anthropic"] as const)for(const [status,type,message] of [[429,"insufficient_quota","quota"],[429,"rate_limit_error","monthly spend cap reached"],[503,"invalid_request_error","bad request"],[401,"authentication_error","bad key"],[403,"permission_error","denied"],[400,"content_policy_violation","refused"],[429,"unknown","unknown"]] as const){await check(`${provider} terminal ${type}: no extra attempt`,async()=>{globalThis.fetch=async()=>{calls++;return error(status,type,message);};assert.equal(await completeJson({...config,provider},{...base,failover:{...failover(),alternate:provider==="openai"?alternate:config}}),null);assert.equal(calls,1);});}
 await check("recognized token rate limit is eligible",async()=>{globalThis.fetch=async()=>++calls===1?error(429,"rate_limit_exceeded","tokens per minute"):ok("anthropic");assert(await completeJson(config,{...base,failover:failover()}));assert.equal(calls,2);});
 await check("caller cancellation before or during request never switches",async()=>{for(const before of [true,false]){calls=0;const controller=new AbortController();if(before)controller.abort();globalThis.fetch=async()=>{calls++;controller.abort();throw new DOMException("Cancelled","AbortError");};assert.equal(await completeJson(config,{...base,signal:controller.signal,failover:failover()}),null);assert.equal(calls,before?0:1);}});
 await check("deadline consumed by primary: no fresh timeout for fallback",async()=>{globalThis.fetch=async()=>{calls++;return new Promise<Response>(()=>{});};assert.equal(await completeJson(config,{...base,failover:{...failover(),totalTimeoutMs:30,attemptTimeoutMs:30,minRemainingMs:10}}),null);assert.equal(calls,1);});
 await check("attempt timeout can switch only within original remaining deadline",async()=>{const start=Date.now();globalThis.fetch=async()=>++calls===1?new Promise<Response>(()=>{}):ok("anthropic");assert(await completeJson(config,{...base,failover:{...failover(),totalTimeoutMs:300,attemptTimeoutMs:20}}));assert.equal(calls,2);assert(Date.now()-start<300);});
 await check("shared cost reservation denial prevents alternate",async()=>{let attempts=0;globalThis.fetch=async()=>{calls++;return error();};assert.equal(await completeJson(config,{...base,failover:{...failover(),reserve:async()=>++attempts===1}}),null);assert.equal(calls,1);assert.equal(attempts,2);});
 await check("missing budget gate and unqualified model fail closed",async()=>{process.env.INTAKE_HELP_FAILOVER_POLICY=JSON.stringify({primary:"openai",fallback:"anthropic",totalTimeoutMs:1000,attemptTimeoutMs:400,minRemainingMs:5,allowedErrors:["unavailable"],qualifiedModels:[{provider:"openai",model:"mock-primary"},{provider:"anthropic",model:"mock-backup"}]});globalThis.fetch=async()=>{calls++;return error();};const configured=resolveIntakeLLMConfig("synthetic","help")!;assert(configured);assert.equal(await completeJson(configured,base),null);assert.equal(calls,0);const raw=JSON.parse(process.env.INTAKE_HELP_FAILOVER_POLICY);raw.qualifiedModels=[];process.env.INTAKE_HELP_FAILOVER_POLICY=JSON.stringify(raw);assert.equal(resolveIntakeLLMConfig("synthetic","help"),null);delete process.env.INTAKE_HELP_FAILOVER_POLICY;});
 for(const invalid of ["bad-json",JSON.stringify({wrong:true})])await check("invalid output not success or failover: "+invalid,async()=>{globalThis.fetch=async()=>{calls++;return Response.json({status:"completed",output_text:invalid});};assert.equal(await completeJson(config,{...base,failover:failover()}),null);assert.equal(calls,1);});
 await check("both providers fail, no sample response",async()=>{globalThis.fetch=async()=>{calls++;return error();};assert.equal(await completeJson(config,{...base,failover:failover()}),null);assert.equal(calls,2);});
 await check("unclassified HTTP 503 remains unavailable but cannot trigger failover",async()=>{globalThis.fetch=async()=>{calls++;return Response.json({},{status:503});};let failure="";assert.equal(await completeJson(config,{...base,failover:failover(),onFailure:e=>failure=e.code}),null);assert.equal(calls,1);assert.equal(failure,"unavailable");});
 await check("visible partial stream never appends another provider",async()=>{const chunks:string[]=[];globalThis.fetch=async()=>{calls++;return new Response('data: {"type":"response.output_text.delta","delta":"partial"}\n\ndata: {"type":"response.failed"}\n\n');};assert.equal(await streamText(config,base,s=>chunks.push(s)),null);assert.equal(calls,1);assert.deepEqual(chunks,["partial"]);});
 await check("real intake job: fallback, duplicate request, single reply and allowance",async()=>{
  process.env.INTAKE_HELP_FAILOVER_POLICY=JSON.stringify({primary:"openai",fallback:"anthropic",totalTimeoutMs:1000,attemptTimeoutMs:400,minRemainingMs:5,allowedErrors:["unavailable"],qualifiedModels:[{provider:"openai",model:"mock-primary"},{provider:"anthropic",model:"mock-backup"}]});
  const owner="failover-"+randomUUID();const started=await saveIntakeCommand(owner,{action:"start",mode:"startup",revision:0,requestId:randomUUID()});
  const command={action:"help" as const,message:"고객 항목이 뭐예요?",planId:started.plan.id,revision:started.snapshot.coach.revision,requestId:randomUUID()};
  const queued=await saveIntakeCommand(owner,command,{aiAvailable:true,aiAllowed:true});assert((await saveIntakeCommand(owner,command,{aiAvailable:true,aiAllowed:true})).duplicate);
  const request={ownerHash:owner,planId:queued.plan.id,jobId:queued.job!.id};let reservations=0;
  globalThis.fetch=async()=>++calls===1?error():ok("anthropic");
  assert((await executeIntakeJob(request,{reserveCost:async()=>{reservations++;return true;}})).ok);await executeIntakeJob(request,{reserveCost:async()=>{reservations++;return true;}});
  const plan=(await loadPlanState(owner)).plans.find(p=>p.id===queued.plan.id)!;assert.equal(readIntake(plan.answers)!.job!.status,"complete");assert.equal(readCoach(plan.answers)!.messages.filter(m=>m.id===queued.job!.id+":reply").length,1);assert.equal(calls,2);assert.equal(reservations,2);
  delete process.env.INTAKE_HELP_FAILOVER_POLICY;
 });
 await check("real intake failure retains request and retry path",async()=>{
  process.env.INTAKE_HELP_FAILOVER_POLICY=JSON.stringify({primary:"openai",fallback:"anthropic",totalTimeoutMs:1000,attemptTimeoutMs:400,minRemainingMs:5,allowedErrors:["unavailable"],qualifiedModels:[{provider:"openai",model:"mock-primary"},{provider:"anthropic",model:"mock-backup"}]});
  const owner="failure-"+randomUUID(),start=await saveIntakeCommand(owner,{action:"start",mode:"startup",revision:0,requestId:randomUUID()});
  const queued=await saveIntakeCommand(owner,{action:"help",message:"원문을 보존해줘",planId:start.plan.id,revision:start.snapshot.coach.revision,requestId:randomUUID()},{aiAvailable:true,aiAllowed:true});globalThis.fetch=async()=>{calls++;return error();};assert.equal((await executeIntakeJob({ownerHash:owner,planId:queued.plan.id,jobId:queued.job!.id},{reserveCost:async()=>true})).ok,false);const plan=(await loadPlanState(owner)).plans.find(p=>p.id===queued.plan.id)!;const job=readIntake(plan.answers)!.job!;assert.equal(job.status,"failed");assert.equal(job.request,"원문을 보존해줘");assert(job.error?.includes("다시"));assert.equal(calls,2);delete process.env.INTAKE_HELP_FAILOVER_POLICY;
 });
 await check("all four features resolve independent policies and retain hard timeout caps",async()=>{
  for(const feature of ["ideas","design","help","extract"] as const){const key=`INTAKE_${feature.toUpperCase()}_FAILOVER_POLICY`;process.env[key]=JSON.stringify({primary:"openai",fallback:"anthropic",totalTimeoutMs:60000,attemptTimeoutMs:10000,minRemainingMs:500,allowedErrors:["unavailable"],qualifiedModels:[{provider:"openai",model:"mock-primary"},{provider:"anthropic",model:"mock-backup"}]});const c=resolveIntakeLLMConfig("synthetic",feature,async()=>true)!;assert.equal(c.execution!.totalTimeoutMs,feature==="design"||feature==="ideas"?60000:20000);assert.deepEqual(c.execution!.allowedErrors,["unavailable"]);delete process.env[key];}
 });
 for(const feature of ["ideas","design","extract"] as const)await check(`real ${feature} job validates and saves fallback output`,async()=>{
  const key=`INTAKE_${feature.toUpperCase()}_FAILOVER_POLICY`;process.env[key]=JSON.stringify({primary:"openai",fallback:"anthropic",totalTimeoutMs:1000,attemptTimeoutMs:400,minRemainingMs:5,allowedErrors:["unavailable"],qualifiedModels:[{provider:"openai",model:"mock-primary"},{provider:"anthropic",model:"mock-backup"}]});
  const owner=feature+randomUUID();let state=await saveIntakeCommand(owner,{action:"start",mode:feature==="ideas"?"exploring":"startup",questionId:feature==="design"?"business":undefined,value:feature==="design"?"온라인 사진 편집 서비스":undefined,revision:0,requestId:randomUUID()});
  if(feature==="extract")state=await saveIntakeCommand(owner,{action:"note",message:"직장인을 돕는 일을 해보고 싶어요",planId:state.plan.id,revision:state.snapshot.coach.revision,requestId:randomUUID()});
  const queued=await saveIntakeCommand(owner,{action:feature,message:feature==="ideas"?"새로운 방향으로 제안해줘":undefined,planId:state.plan.id,revision:state.snapshot.coach.revision,requestId:randomUUID()},{aiAvailable:true,aiAllowed:true});
  const idea=(n:number)=>({title:`합성 후보 ${n}`,description:`설명 ${n}`,customer:`고객 ${n}`,problem:`문제 ${n}`,offering:`제공 ${n}`,delivery:`방식 ${n}`,revenue:`대가 ${n}`,differences:`차이 ${n}`,unknowns:["실제 검증 필요"],structure:{payer:"b2b",offering:"service",delivery:"online",revenue:"project"}});
  const value=feature==="ideas"?{ideas:[idea(1),idea(2)]}:feature==="extract"?{candidates:[]}:{approach:"known-business",startingPlan:{scope:"합성 계획",connectionToVision:"합성 연결",whyThis:"합성 이유",notIncluded:["실제 검증"]},alternatives:[{name:"합성 대안",scope:"합성 범위",tradeoff:"합성 차이"}],assumptions:[{statement:"합성 가정",howToCheck:"별도 검증"}],nextAction:{action:"합성 행동",doneWhen:"합성 완료",usableText:"합성 문구"}};
  globalThis.fetch=async()=>++calls===1?error():ok("anthropic",value);assert(queued.job);assert((await executeIntakeJob({ownerHash:owner,planId:queued.plan.id,jobId:queued.job.id},{reserveCost:async()=>true})).ok);const plan=(await loadPlanState(owner)).plans.find(p=>p.id===state.plan.id)!;assert.equal(readIntake(plan.answers)!.job!.status,"complete");assert.equal(calls,2);delete process.env[key];
 });
 await check("fallback result after business condition change cannot save",async()=>{
  process.env.INTAKE_HELP_FAILOVER_POLICY=JSON.stringify({primary:"openai",fallback:"anthropic",totalTimeoutMs:1000,attemptTimeoutMs:400,minRemainingMs:5,allowedErrors:["unavailable"],qualifiedModels:[{provider:"openai",model:"mock-primary"},{provider:"anthropic",model:"mock-backup"}]});
  const owner="stale-"+randomUUID(),start=await saveIntakeCommand(owner,{action:"start",mode:"startup",revision:0,requestId:randomUUID()});
  const queued=await saveIntakeCommand(owner,{action:"help",message:"현재 예산으로 가능한가요",planId:start.plan.id,revision:start.snapshot.coach.revision,requestId:randomUUID()},{aiAvailable:true,aiAllowed:true});
  let release!:(r:Response)=>void,entered!:()=>void;const waiting=new Promise<void>(r=>entered=r);
  globalThis.fetch=async()=>{calls++;if(calls===1)return error();entered();return new Promise<Response>(r=>release=r);};
  const running=executeIntakeJob({ownerHash:owner,planId:queued.plan.id,jobId:queued.job!.id},{reserveCost:async()=>true});await waiting;
  const current=(await loadPlanState(owner)).plans.find(p=>p.id===queued.plan.id)!;
  await saveIntakeCommand(owner,{action:"resources",resourceLimits:{monthlyOperatingCost:"0원"},planId:current.id,revision:readCoach(current.answers)!.revision,requestId:randomUUID()});
  release(ok("anthropic"));assert.equal((await running).ok,false);const after=(await loadPlanState(owner)).plans.find(p=>p.id===current.id)!;assert.equal(readIntake(after.answers)!.job!.status,"failed");assert.equal(readCoach(after.answers)!.messages.filter(m=>m.id===queued.job!.id+":reply").length,0);delete process.env.INTAKE_HELP_FAILOVER_POLICY;
 });
 console.log(JSON.stringify({failures,realExternalCalls:0}));process.exitCode=failures?1:0;
}
// Keep the event loop alive when intentionally mocked fetch ignores AbortSignal.
const keepAlive=setInterval(()=>{},1000);main().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>clearInterval(keepAlive));
