import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { OPERATING_KEY, OperatingError, applyOperatingCommand, comparePeriods, oldInput, periodDays, periodInputSchema, previousPeriod, readOperatingState, referenceFor, reportIsCurrent, reportMarkdown, resolvePeriodReference, type OperatingCommand, type PeriodInput } from "../lib/plan-builder/operating-records";
import { loadOperatingRecords, saveOperatingRecords } from "../lib/plan-builder/operating-records-service";
import { loadPlanState, normalizeState, preserveServerCoachRecords, savePlanState } from "../lib/plan-builder/plan-server-store";
import { emptyCoach } from "../lib/plan-builder/coach-job";
import { COACH_KEY } from "../lib/plan-builder/coach";

const at = "2026-01-01T00:00:00.000Z";
const input: PeriodInput = { start: "2026-08-01", end: "2026-08-07", metrics: { inquiries: null, orders: 0, revenue: 100000, expenses: 50000 }, feedback: "직접 들은 고객 반응", keep: "촬영 품질", change: "문의 응대", nextAction: "첫 답변을 하루 안에 보내기", successCriterion: "다음 주 문의 응답 시간을 기록하기" };
function rejectsCode(fn: () => unknown, code: string) { assert.throws(fn, error => error instanceof OperatingError && error.code === code); }
async function main() {
  Object.assign(process.env, { PERSISTENCE_MODE: "demo-memory", SUPABASE_URL: "", SUPABASE_SERVICE_ROLE_KEY: "" });
  const first = randomUUID(), second = randomUUID();
  const create: OperatingCommand = { action: "save", id: first, expectedRevision: null, input };
  const empty = readOperatingState({});
  let state = applyOperatingCommand(empty, create, "테스트 사업", at);
  assert.equal(state.periods.length, 1);
  assert.equal(state.periods[0].metrics.inquiries, null);
  assert.equal(state.periods[0].metrics.orders, 0);
  assert.equal(periodDays(input), 7);
  assert.equal(periodDays({ start: "2024-02-28", end: "2024-03-01" }), 3);
  assert.equal(applyOperatingCommand(state, create, "테스트 사업", at), state, "lost create response is idempotent");
  assert.equal(periodInputSchema.safeParse({ ...input, end: "2026-07-31" }).success, false);
  assert.equal(periodInputSchema.safeParse({ ...input, start: "2026-02-30" }).success, false);
  assert.equal(periodInputSchema.safeParse({ ...input, metrics: { ...input.metrics, revenue: -1 } }).success, false);
  assert.equal(periodInputSchema.safeParse({ ...input, metrics: { ...input.metrics, orders: 1.5 } }).success, false);
  rejectsCode(() => readOperatingState({ [OPERATING_KEY]: { version: 0 } }), "INVALID_STORED_RECORD");
  rejectsCode(() => applyOperatingCommand(state, { ...create, id: randomUUID() }, "test", at), "PERIOD_OVERLAP");
  rejectsCode(() => applyOperatingCommand(empty, { ...create, input: { ...input, metrics: { inquiries: null, orders: null, revenue: null, expenses: null }, feedback: "" } }, "test", at), "EMPTY_PERIOD");
  state = applyOperatingCommand(state, { ...create, id: second, input: { ...input, start: "2026-08-08", end: "2026-08-21", metrics: { inquiries: 3, orders: 2, revenue: 150000, expenses: null } } }, "test", at);
  const period = state.periods.find(p => p.id === second)!;
  const baseline = previousPeriod(state.periods, period)!;
  assert.equal(baseline.id, first);
  assert.equal(previousPeriod(state.periods, baseline), null);
  const rows = comparePeriods(period, baseline);
  assert.equal(rows[0].delta, null, "unknown inquiries must not be treated as zero");
  assert.equal(rows[1].delta, 2);
  assert.equal(rows[1].percent, null, "division by zero is not an improvement percentage");
  assert.equal(rows[2].delta, 50000);
  assert.equal(rows[2].percent, 50);
  assert.equal(rows[3].delta, null);
  const ref = referenceFor(period, baseline);
  const archive: OperatingCommand = { action: "report", id: randomUUID(), reference: ref };
  rejectsCode(() => applyOperatingCommand({ ...state, periods: state.periods.map(p => ({ ...p, nextAction: "" })) }, archive, "test", at), "ACTION_REQUIRED");
  const archived = applyOperatingCommand(state, archive, "테스트 사업", at);
  assert.equal(reportIsCurrent(archived, archived.reports[0]), true);
  assert.equal(archived.reports.length, 1);
  assert.equal(applyOperatingCommand(archived, archive, "test", at), archived, "archive retry must not duplicate reports");
  rejectsCode(() => applyOperatingCommand(archived, { ...archive, id: randomUUID() }, "test", at), "REPORT_EXISTS");
  const editedInput = { ...oldInput(period), metrics: { ...period.metrics, revenue: 900000 } };
  const edited = applyOperatingCommand(archived, { action: "save", id: second, expectedRevision: 1, input: editedInput }, "test", at);
  assert.equal(edited.reports[0].period.metrics.revenue, 150000, "snapshot does not change after source edits");
  assert.equal(edited.reports[0].baseline?.metrics.revenue, 100000);
  assert.equal(applyOperatingCommand(edited, archive, "test", at), edited, "old archive response can be replayed after source changes");
  rejectsCode(() => resolvePeriodReference(edited, ref), "PERIOD_CHANGED");
  rejectsCode(() => applyOperatingCommand(edited, { action: "save", id: second, expectedRevision: 1, input: { ...editedInput, change: "다른 탭" } }, "test", at), "PERIOD_CHANGED");
  const editedBaseline = applyOperatingCommand(archived, { action: "save", id: first, expectedRevision: 1, input: { ...input, feedback: "나중에 수정한 고객 반응" } }, "test", at);
  rejectsCode(() => resolvePeriodReference(editedBaseline, ref), "PERIOD_CHANGED");
  assert.equal(editedBaseline.reports[0].baseline?.feedback, input.feedback);
  assert.equal(reportIsCurrent(editedBaseline, editedBaseline.reports[0]), false);
  assert.equal(reportIsCurrent(edited, edited.reports[0]), false);
  assert.match(reportMarkdown(archived.reports[0]), /기간 길이가 달라/);
  assert.match(reportMarkdown(archived.reports[0]), /AI 분석이나 실적 검증 결과가 아닙니다/);
  assert.match(reportMarkdown(archived.reports[0]), /직접 들은 고객 반응/);
  assert.equal(archived.reports[0].source, "user-records");

  const owner = "operating-record-owner", planId = "operating-record-plan";
  await savePlanState(owner, normalizeState({ plans: [{ id: planId, title: "운영 기록 테스트", planType: "일반 사업계획서", createdAt: at, updatedAt: at, answers: { [COACH_KEY]: { state: emptyCoach() } }, sections: {} }] }));
  const staleWorker = await loadPlanState(owner);
  const commandA: OperatingCommand = { ...create, id: randomUUID() };
  const commandB: OperatingCommand = { ...create, id: randomUUID(), input: { ...input, start: "2026-08-08", end: "2026-08-14" } };
  await Promise.all([saveOperatingRecords(owner, planId, commandA), saveOperatingRecords(owner, planId, commandB)]);
  let saved = (await loadOperatingRecords(owner, planId)).records;
  assert.equal(saved.periods.length, 2, "concurrent different periods are both kept");
  const racing = saved.periods[0];
  const outcomes = await Promise.allSettled([
    saveOperatingRecords(owner, planId, { action: "save", id: racing.id, expectedRevision: racing.revision, input: { ...oldInput(racing), feedback: "탭 A" } }),
    saveOperatingRecords(owner, planId, { action: "save", id: racing.id, expectedRevision: racing.revision, input: { ...oldInput(racing), feedback: "탭 B" } }),
  ]);
  assert.equal(outcomes.filter(result => result.status === "fulfilled").length, 1, "only one same-period edit can succeed");
  assert.equal(outcomes.filter(result => result.status === "rejected").length, 1);
  saved = (await loadOperatingRecords(owner, planId)).records;
  const beforeWorker = structuredClone(saved);
  staleWorker.plans[0].updatedAt = "2099-01-01T00:00:00.000Z";
  staleWorker.plans[0].answers[COACH_KEY] = { state: { ...emptyCoach(), revision: 5 } };
  staleWorker.plans[0].sections["overview/summary"] = { markdown: "문서 생성 결과", html: "<p>문서 생성 결과</p>", generatedAt: at };
  await savePlanState(owner, staleWorker);
  assert.deepEqual((await loadOperatingRecords(owner, planId)).records, beforeWorker, "old server workers cannot erase period records");
  const currentState = await loadPlanState(owner);
  const forged = structuredClone(currentState);
  forged.plans[0].answers[OPERATING_KEY] = { ...empty, revision: 999999 };
  await savePlanState(owner, preserveServerCoachRecords(forged, currentState));
  assert.deepEqual((await loadOperatingRecords(owner, planId)).records, beforeWorker, "generic browser autosave cannot forge operating revisions");
  await assert.rejects(loadOperatingRecords("other-owner", planId), error => error instanceof OperatingError && error.status === 404);
  await assert.rejects(saveOperatingRecords("other-owner", planId, commandA), error => error instanceof OperatingError && error.status === 404);
  const latest = saved.periods[0], previous = previousPeriod(saved.periods, latest);
  const commandReport: OperatingCommand = { action: "report", id: randomUUID(), reference: referenceFor(latest, previous) };
  await Promise.all([saveOperatingRecords(owner, planId, commandReport), saveOperatingRecords(owner, planId, commandReport)]);
  assert.equal((await loadOperatingRecords(owner, planId)).records.reports.length, 1);
  assert.equal((await loadPlanState(owner)).plans[0].sections["overview/summary"].markdown, "문서 생성 결과");
  console.log("operating records: validation, sparse comparisons, immutable reports, retries, concurrent edits, worker/autosave preservation and ownership passed");
}
void main().catch(error => { console.error(error); process.exitCode = 1; });
