import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { previousPeriod, referenceFor, type OperatingState, type PeriodInput } from "../lib/plan-builder/operating-records";

// Fixed, guarded in-memory lab only. No production credentials or external AI calls.
const base = "http://127.0.0.1:8095";
let cookie = "";
const request = (path: string, method = "GET", body?: unknown, owner = cookie) => fetch(`${base}${path}`, { method, headers: { "Content-Type": "application/json", Cookie: owner }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
const fixture = await request("/api/dev/business-journeys", "POST");
assert.equal(fixture.status, 200);
cookie = fixture.headers.getSetCookie().map(v => v.split(";")[0]).join("; ");
assert.ok(cookie);
const planId = new URL((await fixture.json()).href, base).searchParams.get("planId")!;
const path = `/api/plan/operations?planId=${planId}`;
const post = (command: unknown) => request("/api/plan/operations", "POST", { planId, command });
const analyze = (body: unknown, owner = cookie) => request("/api/plan/operations/analysis", "POST", { planId, ...body as object }, owner);
assert.equal((await (await request(path)).json()).analysisTarget.provider, "mock");
const input: PeriodInput = { start: "2026-08-01", end: "2026-08-07", metrics: { inquiries: 4, orders: 1, revenue: 100000, expenses: null }, feedback: "EXCLUDED_CUSTOMER_NOTE", keep: "EXCLUDED_KEEP", change: "", nextAction: "", successCriterion: "" };
assert.equal((await post({ action: "save", id: randomUUID(), expectedRevision: null, input })).status, 200);
assert.equal((await post({ action: "save", id: randomUUID(), expectedRevision: null, input: { ...input, start: "2026-08-08", end: "2026-08-14", metrics: { ...input.metrics, inquiries: 8, revenue: 180000 } } })).status, 200);
let records: OperatingState = (await (await request(path)).json()).records;
const period = records.periods[0];
const selection = { feedback: false, notes: false };
const reference = referenceFor(period, previousPeriod(records.periods, period));
const previewResponse = await analyze({ action: "preview", reference, selection });
assert.equal(previewResponse.status, 200);
assert.match(previewResponse.headers.get("cache-control")!, /no-store/);
const { preview } = await previewResponse.json();
assert.doesNotMatch(JSON.stringify(preview.payload), /EXCLUDED/);
assert.equal((await (await request(path)).json()).records.analyses.length, 0);
const body = { action: "generate", id: randomUUID(), reference, selection, consent: { accepted: true, version: preview.version, hash: preview.hash, target: preview.target } };
assert.equal((await analyze({ ...body, consent: { ...body.consent, accepted: false } })).status, 400);
assert.equal((await analyze({ ...body, consent: { ...body.consent, hash: "a".repeat(64) } })).status, 409);
assert.equal((await analyze(body, "")).status, 404);
const generated = await analyze(body);
assert.equal(generated.status, 200);
records = (await generated.json()).records;
assert.equal(records.analyses[0].status, "ready");
assert.equal(records.analyses[0].consent.target.provider, "mock");
assert.equal((await analyze(body)).status, 200);
assert.equal((await (await request(path)).json()).records.analyses.length, 1);
const archive = { action: "analysis-report", id: randomUUID(), analysisId: body.id, chosenAction: { index: 0, action: "직접 수정한 안내 문구로 다음 기간 관찰", successCriterion: "같은 질문의 반복 횟수 기록" } };
assert.equal((await post(archive)).status, 200);
assert.equal((await post(archive)).status, 200);
records = (await (await request(path)).json()).records;
assert.equal(records.reports.length, 1);
assert.equal(records.reports[0].chosenAction?.action, archive.chosenAction.action);
assert.equal(records.periods[0].nextAction, "");
const download = await request(`${path}&reportId=${archive.id}`);
assert.equal(download.status, 200);
assert.match(download.headers.get("content-disposition")!, /^attachment;/);
const markdown = await download.text();
assert.match(markdown, /로컬 모의 AI/);
assert.match(markdown, /직접 수정한 안내 문구/);
assert.match(markdown, /확인이 필요한 가설|원인 가설/);
assert.equal((await request(`${path}&reportId=${archive.id}`, "GET", undefined, "")).status, 404);
assert.equal((await post({ action: "save", id: period.id, expectedRevision: 1, input: { ...input, start: period.start, end: period.end, feedback: "다른 탭 수정" } })).status, 200);
assert.equal((await analyze({ ...body, id: randomUUID() })).status, 409);
records = (await (await request(path)).json()).records;
assert.equal(records.reports[0].period.metrics.revenue, 180000);
assert.equal(records.periods[0].metrics.revenue, 100000);
console.log("operating analysis HTTP lab: consent, minimized preview, owner isolation, mock generation, retry, edited-action archive, reload/download and stale-source rejection passed");
