import assert from "node:assert/strict";
import { prelaunchLifecycleScope } from "./prelaunch-lifecycle-safety";
import { PRELAUNCH_ORIGIN } from "./prelaunch-db-safety";
const scope = prelaunchLifecycleScope("0123456789abcdef");
scope.owners.add("a".repeat(64)); scope.owners.add("b".repeat(64)); scope.users.add("qa-user"); scope.projects.add("qa-project"); scope.sites.add("qa-site"); scope.slugs.add("qa-slug");
const request = (path: string, method = "GET", body?: Record<string, any>) => scope.assertRequest(new URL(path, PRELAUNCH_ORIGIN), method, body);
const owner = "a".repeat(64), account = "b".repeat(64);
request("/rest/v1/rpc/claim_plan_state", "POST", { p_guest_hash: owner, p_account_hash: account, p_data: { plans: [{ id: `${scope.prefix}plan` }] } });
request("/rest/v1/rpc/ensure_plan_project", "POST", { p_owner_hash: owner, p_owner_id: "qa-user", p_plan_id: `${scope.prefix}plan` });
request("/rest/v1/landing_sites?id=eq.qa-site", "PATCH", { status: "draft", published_slug: null });
request(`/rest/v1/opportunity_preferences?or=(owner_id.eq.qa-user,guest_token_hash.eq.${owner})`);
request("/rest/v1/opportunity_preferences?owner_id=eq.qa-user", "DELETE");
for (const path of ["/rest/v1/projects", "/rest/v1/landing_sites", "/rest/v1/landing_versions", "/rest/v1/plan_owner_claims", "/rest/v1/projects?owner_id=eq.existing", `/rest/v1/projects?guest_token_hash=eq.${owner}&or=(owner_id.neq.x)`]) assert.throws(() => request(path));
assert.throws(() => request("/rest/v1/rpc/claim_plan_state", "POST", { p_guest_hash: owner, p_account_hash: "existing", p_data: { plans: [] } }));
assert.throws(() => request("/rest/v1/rpc/commit_plan_state", "POST", { p_owner_hash: owner, p_delete: true, p_data: { plans: [] } }));
assert.throws(() => request("/rest/v1/rpc/publish_landing_snapshot", "POST", { p_owner_hash: owner, p_project_id: "existing" }));
assert.throws(() => request("/rest/v1/payment_orders", "POST", { status: "paid" }));
assert.throws(() => request("/rest/v1/landing_sites?id=eq.existing", "PATCH", { status: "draft", published_slug: null }));
assert.throws(() => request("/rest/v1/projects?id=eq.qa-project", "DELETE"));
assert.throws(() => request("https://api.openai.com/v1/responses", "POST"));
console.log("Prelaunch lifecycle guard: known synthetic owners/projects/sites, limited RPCs and no payment calls passed");
