import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { seedRewriteFixture, changeFixturePrice, mockRewrite, rewriteRequest } from "./proposal-rewrite-fixture";
import { loadProposalEditor, saveProposalEditor } from "../lib/plan-builder/proposal-editor-service";
import { previewProposalRewrite, runProposalRewrite, type RewriteRuntime } from "../lib/plan-builder/proposal-rewrite-service";
import { loadPlanState, savePlanState } from "../lib/plan-builder/plan-server-store";
import { readSavedProposal } from "../lib/plan-builder/proposal-editor";
import { renderableProposal } from "../lib/plan-builder/proposal-revision";
import { renderDeckPptx } from "../lib/plan-builder/deck-render";
import { pickDeckTheme } from "../lib/plan-builder/deck-themes";
import JSZip from "jszip";

async function main() {
  Object.assign(process.env, { PERSISTENCE_MODE: "demo-memory", SUPABASE_URL: "", SUPABASE_SERVICE_ROLE_KEY: "" });
  const owner = `rewrite-${randomUUID()}`, id = "synthetic-proposal";
  const { commercialKey } = await seedRewriteFixture(owner, id);
  const manual = { "proposal-summary": { text: { title: "내가 쓴 고객 소개" }, layout: { title: { x: 1.1, y: 1.6, w: 9, h: .9 } } }, "proposal-offering": { text: { title: "내가 쓴 제공 범위" } } };
  await saveProposalEditor(owner, id, { type: "save", requestId: randomUUID(), expectedRevision: 1, edits: manual });
  const legacyState = await loadPlanState(owner);
  const legacy = readSavedProposal(legacyState.plans[0].answers)!;
  legacy.history = legacy.history.map(({ revision, savedAt, edits }) => ({ revision, savedAt, edits }));
  await savePlanState(owner, legacyState);
  const before = (await loadProposalEditor(owner, id)).saved!;
  await changeFixturePrice(owner, id, commercialKey);
  let calls = 0;
  const runtime: RewriteRuntime = { target: { provider: "mock", model: "synthetic-only" }, generate: async payload => { calls++; return { result: mockRewrite(payload) }; } };
  const preview = await previewProposalRewrite(owner, id, runtime);
  assert.equal(preview.impact.affected.length, 3);
  assert.equal(preview.impact.affected.filter(item => item.textConflict).length, 2);
  assert(!JSON.stringify(preview.payload).includes("내가 쓴"));
  assert(!JSON.stringify(preview.payload).includes('"placement"'));
  assert(!Object.hasOwn(preview.impact.nextSource, "allAnswers"));
  await assert.rejects(() => previewProposalRewrite("other", id, runtime), /찾을 수/);
  const request = rewriteRequest(preview);
  await assert.rejects(() => runProposalRewrite(owner, id, { ...request, consent: false } as any, runtime), /변경 요청/);
  await assert.rejects(() => runProposalRewrite(owner, id, { ...request, hash: "a".repeat(64) }, runtime), /다시 확인/);
  await assert.rejects(() => runProposalRewrite(owner, id, request, null), /검증 중/);
  assert.equal(calls, 0);
  const ready = await runProposalRewrite(owner, id, request, runtime);
  assert.equal(ready.rewrite?.status, "ready"); assert.equal(calls, 1);
  assert.deepEqual(ready.document.edits, before.document.edits);
  await runProposalRewrite(owner, id, request, runtime); assert.equal(calls, 1);
  await assert.rejects(() => runProposalRewrite(owner, id, { ...request, hash: "b".repeat(64) }, runtime), /같은 요청/);
  await assert.rejects(() => runProposalRewrite(owner, id, { type: "apply", id: request.id, expectedRevision: ready.revision, choices: {} }), /선택/);
  const apply = { type: "apply" as const, id: request.id, expectedRevision: ready.revision, choices: { "proposal-summary": "keep_manual" as const, "proposal-offering": "use_revised" as const } };
  const applied = await runProposalRewrite(owner, id, apply);
  assert.equal(applied.rewrite?.status, "applied"); assert.equal((await loadProposalEditor(owner, id)).sourceChanged, true, "Retained manual content requires an explicit fresh review");
  assert.equal(applied.document.edits["proposal-summary"].text?.title, "내가 쓴 고객 소개");
  assert.deepEqual(applied.document.edits["proposal-summary"].layout, manual["proposal-summary"].layout);
  assert.equal(applied.document.edits["proposal-offering"].text, undefined);
  assert.equal((await runProposalRewrite(owner, id, apply)).revision, applied.revision);
  const unchanged = before.document.deck.slides.filter(slide => !preview.impact.affected.some(item => item.slideId === slide.id));
  assert.deepEqual(applied.document.deck.slides.filter(slide => unchanged.some(item => item.id === slide.id)), unchanged);
  const deck = renderableProposal(applied.document);
  const ppt = await renderDeckPptx(deck, pickDeckTheme("", deck.brandName, ""));
  const zip = await JSZip.loadAsync(ppt);
  for (const item of preview.impact.affected) {
    const number = deck.slides.findIndex(slide => slide.id === item.slideId) + 1;
    const xml = await zip.file(`ppt/slides/slide${number}.xml`)!.async("string");
    assert(xml.includes("180만원")); assert(!xml.includes("150만원"));
  }
  const prior = applied.history.at(-1)!;
  assert.equal(prior.reason, "source_update"); assert(prior.document);
  assert.deepEqual(applied.history.find(item => item.revision === 1)?.document?.deck, before.document.deck, "Legacy edit-only versions retain the original deck after a linked update");
  const restored = await saveProposalEditor(owner, id, { type: "restore", requestId: randomUUID(), expectedRevision: applied.revision, revision: prior.revision });
  assert.deepEqual(restored.saved?.document.deck, before.document.deck);
  assert.deepEqual(restored.saved?.document.source, before.document.source);
  assert.equal(restored.saved?.fingerprint, before.fingerprint); assert(restored.sourceChanged);

  const owner2 = `rewrite-race-${randomUUID()}`, id2 = "synthetic-race";
  const seeded = await seedRewriteFixture(owner2, id2); await changeFixturePrice(owner2, id2, seeded.commercialKey);
  let release!: (value: { result: unknown }) => void;
  const slow: RewriteRuntime = { ...runtime, generate: () => new Promise(resolve => { release = resolve; }) };
  const p2 = await previewProposalRewrite(owner2, id2, slow), r2 = rewriteRequest(p2);
  const running = runProposalRewrite(owner2, id2, r2, slow);
  while (!release) await new Promise(resolve => setTimeout(resolve, 5));
  await assert.rejects(() => runProposalRewrite(owner2, id2, rewriteRequest(p2), runtime), /작성 중/);
  await changeFixturePrice(owner2, id2, seeded.commercialKey, "180만원", "200만원");
  release({ result: mockRewrite(p2.payload) });
  assert.equal((await running).rewrite?.error, "source_changed");
  const failed = await loadProposalEditor(owner2, id2);
  assert.equal(failed.saved?.document.deck.slides.find(slide => slide.id === "proposal-commercial")?.table?.rows[0][1], "150만원");
  const p3 = await previewProposalRewrite(owner2, id2, runtime);
  const broken: RewriteRuntime = { ...runtime, generate: async () => { throw new Error("timeout"); } };
  const timedOut = await runProposalRewrite(owner2, id2, rewriteRequest(p3), broken);
  assert.equal(timedOut.rewrite?.error, "timeout");
  const p4 = await previewProposalRewrite(owner2, id2, runtime);
  const invalid: RewriteRuntime = { ...runtime, generate: async payload => ({ result: { slides: [mockRewrite(payload).slides[0], mockRewrite(payload).slides[0]] } }) };
  assert.equal((await runProposalRewrite(owner2, id2, rewriteRequest(p4), invalid)).rewrite?.error, "invalid_response");
  await assert.rejects(() => runProposalRewrite(owner2, id2, rewriteRequest(p4), runtime), /한도/);

  const owner3 = `rewrite-edit-${randomUUID()}`, id3 = "synthetic-edit";
  const third = await seedRewriteFixture(owner3, id3); await changeFixturePrice(owner3, id3, third.commercialKey);
  const p5 = await previewProposalRewrite(owner3, id3, runtime), r5 = rewriteRequest(p5);
  const result = await runProposalRewrite(owner3, id3, r5, runtime);
  await saveProposalEditor(owner3, id3, { type: "save", requestId: randomUUID(), expectedRevision: result.revision, edits: { "proposal-cover": { text: { title: "다른 탭에서 편집" } } } });
  const latest = (await loadProposalEditor(owner3, id3)).saved!;
  await assert.rejects(() => runProposalRewrite(owner3, id3, { type: "apply", id: r5.id, expectedRevision: latest.revision, choices: {} }), /바뀌었어요/);
  const dismissed = await runProposalRewrite(owner3, id3, { type: "dismiss", id: r5.id });
  assert.equal(dismissed.rewrite?.status, "dismissed");
  const protectedState = await loadPlanState(owner3);
  assert.equal(readSavedProposal(protectedState.plans[0].answers)?.document.edits["proposal-cover"].text?.title, "다른 탭에서 편집");
  protectedState.plans[0].sections[third.keys[0]].markdown += " 추가 변경";
  await savePlanState(owner3, protectedState);
  const owner4 = `rewrite-jsonb-${randomUUID()}`, id4 = "synthetic-jsonb";
  const fourth = await seedRewriteFixture(owner4, id4); await changeFixturePrice(owner4, id4, fourth.commercialKey);
  const p6 = await previewProposalRewrite(owner4, id4, runtime);
  const reordered = await loadPlanState(owner4);
  const record = readSavedProposal(reordered.plans[0].answers)!;
  record.document = JSON.parse(JSON.stringify(record.document, (_key, value) => value && typeof value === "object" && !Array.isArray(value) ? Object.fromEntries(Object.entries(value).reverse()) : value));
  await savePlanState(owner4, reordered);
  assert.equal((await previewProposalRewrite(owner4, id4, runtime)).hash, p6.hash, "JSON key order cannot invalidate an approved input");
  const r6 = rewriteRequest(p6);
  let finish!: (value: { result: unknown }) => void;
  const cancelRuntime: RewriteRuntime = { ...runtime, generate: () => new Promise(resolve => { finish = resolve; }) };
  const cancelled = runProposalRewrite(owner4, id4, r6, cancelRuntime);
  while (!finish) await new Promise(resolve => setTimeout(resolve, 5));
  await runProposalRewrite(owner4, id4, { type: "dismiss", id: r6.id });
  finish({ result: mockRewrite(p6.payload) });
  assert.equal((await cancelled).rewrite?.status, "dismissed", "Late AI completion cannot resurrect a cancelled result");
  console.log("proposal rewrite: 3-page price propagation, manual conflicts, unchanged pages, native PPT, full restore, ownership, explicit consent, idempotency, concurrent source/edit changes, timeout, invalid output and call limits passed");
}
void main().catch(error => { console.error(error); process.exitCode = 1; });
