import assert from "node:assert/strict";
import { proposalFixture } from "./proposal-fixtures";
import { previewProposalSourceChange, approveProposalSourceChange, undoProposalSourceChange, setProposalSlideEdits, renderableProposal, type ProposalDocument } from "../lib/plan-builder/proposal-revision";

const fixture = proposalFixture();
const initial: ProposalDocument = { revision: 1, ...fixture, edits: {} };
const customized = setProposalSlideEdits(initial, "proposal-offering", { text: { title: "고객과 합의할 제공 범위" }, layout: { title: { x: 1, y: 1.2, w: 10, h: 1 } } }, 1);
const source = structuredClone(customized.source);
source.sections.find(section => section.sectionTitle === "commercial")!.markdown = "제안 가격 180만원. 같은 제공 범위.";
const preview = previewProposalSourceChange(customized, source);
assert.deepEqual(preview.affected.map(slide => slide.slideId), ["proposal-summary", "proposal-offering", "proposal-commercial"]);
assert.equal(preview.affected.find(slide => slide.slideId === "proposal-offering")?.textConflict, true);
const affected = new Set(preview.affected.map(slide => slide.slideId));
const replacements = customized.deck.slides.filter(slide => affected.has(slide.id!)).map(slide => ({ ...slide, lead: "제안 가격 180만원" }));
assert.throws(() => approveProposalSourceChange(customized, preview, replacements), /manual_text_conflict/);
assert.throws(() => approveProposalSourceChange(customized, preview, replacements.slice(1)), /replacement_mismatch/);
assert.throws(() => approveProposalSourceChange(customized, preview, replacements.map(slide => ({ ...slide, sourceSections: ["Invented"] }))), /source_review_required/);
const applied = approveProposalSourceChange(customized, preview, replacements, { "proposal-offering": "keep_manual" });
const renderable = renderableProposal(applied.document);
assert.equal(renderable.slides.find(slide => slide.id === "proposal-offering")?.title, "고객과 합의할 제공 범위");
assert.deepEqual(renderable.slides.find(slide => slide.id === "proposal-offering")?.placement?.title, customized.edits["proposal-offering"].layout?.title);
assert.equal(applied.document.deck.slides.filter(slide => slide.lead === "제안 가격 180만원").length, 3);
assert.deepEqual(applied.document.deck.slides.find(slide => slide.id === "proposal-workflow"), initial.deck.slides.find(slide => slide.id === "proposal-workflow"));
assert.throws(() => approveProposalSourceChange(applied.document, preview, replacements), /revision_conflict/);
const undone = undoProposalSourceChange(applied.document, applied.receipt);
assert.equal(undone.revision, applied.document.revision + 1);
assert.deepEqual(undone.deck, customized.deck);
assert.deepEqual(undone.edits, customized.edits);
assert.deepEqual(initial.edits, {}, "Edits and revisions must not mutate earlier snapshots");
assert.throws(() => setProposalSlideEdits(initial, "proposal-cover", { layout: { title: { x: 12, y: 1, w: 3, h: 1 } } }, 1), /out_of_bounds/);
assert.throws(() => setProposalSlideEdits(initial, "proposal-cover", { layout: { title: { x: NaN, y: 1, w: 3, h: 1 } } }, 1), /out_of_bounds/);
const overwritten = approveProposalSourceChange(customized, preview, replacements, { "proposal-offering": "use_revised" });
assert.equal(overwritten.document.edits["proposal-offering"].text, undefined);
assert.ok(overwritten.document.edits["proposal-offering"].layout?.title);
const renamed = previewProposalSourceChange(initial, { ...initial.source, businessName: "새 사업명" });
assert.equal(renamed.affected.length, initial.deck.slides.length);
assert.equal(previewProposalSourceChange(initial, initial.source).affected.length, 0);
const imageDocument = structuredClone(initial);
imageDocument.deck.slides.find(slide => slide.id === "proposal-offering")!.image = { id: "approved-fixture", data: "data:image/png;base64,AAAA", alt: "가상 이미지" };
const imagePreview = previewProposalSourceChange(imageDocument, source);
const imageUpdate = approveProposalSourceChange(imageDocument, imagePreview, replacements);
assert.deepEqual(imageUpdate.document.deck.slides.find(slide => slide.id === "proposal-offering")!.image, imageDocument.deck.slides.find(slide => slide.id === "proposal-offering")!.image, "Text rewriting cannot replace or remove the approved image");
assert.equal(previewProposalSourceChange(initial, { ...initial.source, sections: [...initial.source.sections, { chapterTitle: "추가 자료", sectionTitle: "실제 매출", markdown: "새로운 자료" }] }).affected.length, initial.deck.slides.length, "New evidence requires review before dependency mappings exist");
console.log("proposal revision: source impact, explicit approval, manual text conflicts, preserved layout, undo and stale revision passed; no AI calls");
