import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { proposalFixture } from "./proposal-fixtures";
import { chaptersForType } from "../lib/plan-builder/blueprint";
import { normalizeState, savePlanState, loadPlanState, preserveServerCoachRecords } from "../lib/plan-builder/plan-server-store";
import { deckFingerprint, deckSource } from "../lib/plan-builder/deck-job";
import { loadProposalEditor, saveProposalEditor } from "../lib/plan-builder/proposal-editor-service";
import { PROPOSAL_KEY, proposalCommandSchema } from "../lib/plan-builder/proposal-editor";
import { renderableProposal } from "../lib/plan-builder/proposal-revision";
import { proposalScenes } from "../lib/plan-builder/proposal-scene";

async function main() {
  Object.assign(process.env, { PERSISTENCE_MODE: "demo-memory", SUPABASE_URL: "", SUPABASE_SERVICE_ROLE_KEY: "" });
  const fixture = proposalFixture(); const at = new Date().toISOString();
  const keys = chaptersForType("").flatMap(ch => ch.sections.map(section => `${ch.id}/${section.id}`)).slice(0, 12);
  const state = normalizeState({ business: { name: fixture.source.businessName, description: fixture.source.businessDescription!, role: "", region: "", industry: "", stage: "" }, activePlanId: "proposal-qa", plans: [{ id: "proposal-qa", title: fixture.source.businessName, planType: "", createdAt: at, updatedAt: at, answers: {}, sections: Object.fromEntries(keys.map((key, i) => [key, { markdown: fixture.source.sections[i].markdown, html: "", generatedAt: at }])) }] });
  const source = deckSource(state.plans[0], state.business); const token = randomUUID();
  const map = new Map(fixture.source.sections.map((s, i) => [`${s.chapterTitle} · ${s.sectionTitle}`, `${source.sections[i].chapterTitle} · ${source.sections[i].sectionTitle}`]));
  fixture.deck.slides.forEach(slide => { slide.sourceSections = slide.sourceSections?.map(name => map.get(name)!); });
  state.plans[0].answers.__deck_job = { token, runId: "fixture", fingerprint: deckFingerprint(source), status: "complete", phase: "ready", attempt: 1, updatedAt: at, result: fixture.deck };
  const owner = `proposal-${randomUUID()}`; await savePlanState(owner, state);
  const failedOwner = `proposal-failed-${randomUUID()}`, failedState = structuredClone(state);
  failedState.plans[0].answers.__deck_job = { ...failedState.plans[0].answers.__deck_job, status: "failed", phase: "failed", result: undefined, draft: fixture.deck, code: "review_response_invalid" };
  await savePlanState(failedOwner, failedState);
  const failedView = await loadProposalEditor(failedOwner, "proposal-qa");
  assert.equal(failedView.generation?.editable, false);
  assert.equal(failedView.generation?.resumable, true);
  assert.equal(failedView.generation?.code, "review_response_invalid");
  assert.equal(failedView.generation?.token, token);
  assert(!("draft" in failedView.generation!) && !("result" in failedView.generation!), "Status view does not send unreviewed slide content");
  await assert.rejects(() => saveProposalEditor(failedOwner, "proposal-qa", { type: "initialize", requestId: randomUUID(), expectedRevision: 0, generationToken: token }), /생성이 완료/);
  await assert.rejects(() => loadProposalEditor("other", "proposal-qa"), /찾을 수/);
  const command = { type: "initialize" as const, requestId: randomUUID(), expectedRevision: 0, generationToken: token };
  const initial = await saveProposalEditor(owner, "proposal-qa", command);
  assert.equal(initial.saved?.revision, 1); assert.equal(initial.saved?.document.deck.slides.length, 12);
  assert.equal((await saveProposalEditor(owner, "proposal-qa", command)).saved?.revision, 1);
  const edit = { type: "save" as const, requestId: randomUUID(), expectedRevision: 1, edits: { "proposal-cover": { text: { title: "직접 편집한 B2B 제안서" }, layout: { title: { x: 1.2, y: 2.1, w: 9, h: 1.5 } } }, "proposal-offering": { content: { table: { headers: ["항목", "범위"], rows: [["납품", "계약 후 2주"]] } } } } };
  const saved = await saveProposalEditor(owner, "proposal-qa", edit);
  assert.equal(saved.saved?.revision, 2); assert.equal(saved.saved?.history.length, 1);
  assert.deepEqual((await loadProposalEditor(owner, "proposal-qa")).saved, saved.saved);
  assert.equal((await saveProposalEditor(owner, "proposal-qa", edit)).saved?.revision, 2);
  await assert.rejects(() => saveProposalEditor(owner, "proposal-qa", { ...edit, requestId: randomUUID() }), /다른 탭/);
  await assert.rejects(() => saveProposalEditor(owner, "proposal-qa", { ...edit, edits: {} }), /요청이 달라/);
  const finalDeck = renderableProposal(saved.saved!.document);
  assert.equal(finalDeck.slides[0].title, "직접 편집한 B2B 제안서");
  const title = proposalScenes(finalDeck)[0].nodes.find(node => node.type === "text" && node.element === "title");
  assert.equal(title?.options.x, 1.2);
  assert.deepEqual(finalDeck.slides.find(slide => slide.id === "proposal-offering")?.table?.rows, [["납품", "계약 후 2주"]]);
  const late = structuredClone(state); late.plans[0].updatedAt = new Date(Date.now() + 100).toISOString();
  await savePlanState(owner, late);
  assert.equal((await loadProposalEditor(owner, "proposal-qa")).saved?.revision, 2, "Late generation workers preserve the editor");
  const forged = structuredClone(late); forged.plans[0].answers[PROPOSAL_KEY] = { version: 1, revision: 9999, document: {} };
  const protectedState = preserveServerCoachRecords(forged, await loadPlanState(owner));
  await savePlanState(owner, protectedState);
  assert.equal((await loadProposalEditor(owner, "proposal-qa")).saved?.revision, 2);
  const restored = await saveProposalEditor(owner, "proposal-qa", { type: "restore", requestId: randomUUID(), expectedRevision: 2, revision: 1 });
  assert.equal(restored.saved?.revision, 3); assert.deepEqual(restored.saved?.document.edits, {});
  await assert.rejects(() => saveProposalEditor(owner, "proposal-qa", edit), /다른 버전/);
  const changed = await loadPlanState(owner); changed.plans[0].sections[keys[0]].markdown += " 원문 변경"; changed.plans[0].updatedAt = new Date(Date.now() + 1000).toISOString(); await savePlanState(owner, changed);
  const stale = await loadProposalEditor(owner, "proposal-qa"); assert.equal(stale.sourceChanged, true); assert(stale.affectedSlides.length); assert.equal(stale.saved?.revision, 3);
  assert(!proposalCommandSchema.safeParse({ ...edit, edits: { "proposal-cover": { image: { data: "bad" } } } }).success);
  assert(!proposalCommandSchema.safeParse({ ...edit, edits: { "proposal-cover": { layout: { title: { x: 13, y: 0, w: 1, h: 1 } } } } }).success);
  assert(!proposalCommandSchema.safeParse({ ...edit, edits: { "proposal-offering": { content: { table: { headers: ["a", "b"], rows: [["a"]] } } } } }).success);
  const pages = stale.saved!.document.pages!;
  const structuredCommand = { type: "save" as const, requestId: randomUUID(), expectedRevision: 3, pages: [{ id: "user-table", layout: "table" as const }, ...pages.slice(1), { ...pages[0], id: "user-copy" }], edits: { "user-table": { text: { title: "직접 만든 표" }, content: { table: { headers: ["항목", "조건"], rows: [["납품물", "검수 후 인계"]] } } }, "user-copy": { text: { title: "보존한 표지 사본" } } } };
  const structured = await saveProposalEditor(owner, "proposal-qa", structuredCommand);
  assert.equal(structured.saved!.document.schemaVersion, 3);
  assert.equal(renderableProposal(structured.saved!.document).slides[0].title, "직접 만든 표");
  assert.equal((await loadProposalEditor(owner, "proposal-qa")).saved!.document.pages!.at(-1)!.id, "user-copy");
  assert.equal((await saveProposalEditor(owner, "proposal-qa", structuredCommand)).saved!.revision, 4);
  await assert.rejects(() => saveProposalEditor(owner, "proposal-qa", { ...structuredCommand, expectedRevision: 4, requestId: randomUUID(), pages: [{ id: "bad", sourceId: "another-owner-slide", layout: "table" }] }), /페이지 순서/);
  const restoredV3 = await saveProposalEditor(owner, "proposal-qa", { type: "restore", requestId: randomUUID(), expectedRevision: 4, revision: 3 });
  assert.deepEqual(restoredV3.saved!.document.pages, pages, "Page structure participates in version restoration");
  console.log("proposal editor: ownership, idempotency, CAS, restore, protected autosave, worker merge, shared geometry, body edits and stale-source preservation passed");
}
void main().catch(error => { console.error(error); process.exitCode = 1; });
