import assert from "node:assert/strict";
import { proposalFixture } from "./proposal-fixtures";
import { previewProposalSourceChange, approveProposalSourceChange, undoProposalSourceChange, setProposalSlideEdits, renderableProposal, upgradeProposalV3, type ProposalDocument } from "../lib/plan-builder/proposal-revision";

const fixture = proposalFixture();
const initial: ProposalDocument = { revision: 1, ...fixture, edits: {} };
const customized = setProposalSlideEdits(initial, "proposal-offering", { text: { title: "고객과 합의할 제공 범위" }, layout: { title: { x: 1, y: 1.2, w: 10, h: 1 } } }, 1);
const source = structuredClone(customized.source);
source.sections.find(section => section.sectionTitle === "commercial")!.markdown = "제안 가격 180만원. 같은 제공 범위.";
const preview = previewProposalSourceChange(customized, source);
assert.deepEqual(preview.affected.map(slide => slide.slideId), ["proposal-summary", "proposal-offering", "proposal-commercial"]);
assert.equal(preview.affected.find(slide => slide.slideId === "proposal-offering")?.textConflict, true);
const affected = new Set(preview.affected.map(slide => slide.slideId));
const replacements = customized.deck.slides.filter(slide => affected.has(slide.id!)).map(slide => ({ ...slide, lead: "제안 가격 180만원" }));
assert.throws(() => approveProposalSourceChange(customized, preview, replacements), /manual_text_conflict/);
assert.throws(() => approveProposalSourceChange(customized, preview, replacements.slice(1)), /replacement_mismatch/);
assert.throws(() => approveProposalSourceChange(customized, preview, replacements.map(slide => ({ ...slide, sourceSections: ["Invented"] }))), /source_review_required/);
const applied = approveProposalSourceChange(customized, preview, replacements, { "proposal-offering": "keep_manual" });
assert.deepEqual(applied.receipt.retainedSlideIds, ["proposal-offering"]);
const renderable = renderableProposal(applied.document);
assert.equal(renderable.slides.find(slide => slide.id === "proposal-offering")?.title, "고객과 합의할 제공 범위");
assert.deepEqual(renderable.slides.find(slide => slide.id === "proposal-offering")?.placement?.title, customized.edits["proposal-offering"].layout?.title);
assert.equal(applied.document.deck.slides.filter(slide => slide.lead === "제안 가격 180만원").length, 3);
assert.deepEqual(applied.document.deck.slides.find(slide => slide.id === "proposal-workflow"), initial.deck.slides.find(slide => slide.id === "proposal-workflow"));
assert.throws(() => approveProposalSourceChange(applied.document, preview, replacements), /revision_conflict/);
const undone = undoProposalSourceChange(applied.document, applied.receipt);
assert.equal(undone.revision, applied.document.revision + 1);
assert.deepEqual(undone.deck, customized.deck);
assert.deepEqual(undone.edits, customized.edits);
assert.deepEqual(initial.edits, {}, "Edits and revisions must not mutate earlier snapshots");
assert.throws(() => setProposalSlideEdits(initial, "proposal-cover", { layout: { title: { x: 12, y: 1, w: 3, h: 1 } } }, 1), /out_of_bounds/);
assert.throws(() => setProposalSlideEdits(initial, "proposal-cover", { layout: { title: { x: NaN, y: 1, w: 3, h: 1 } } }, 1), /out_of_bounds/);
const overwritten = approveProposalSourceChange(customized, preview, replacements, { "proposal-offering": "use_revised" });
assert.equal(overwritten.document.edits["proposal-offering"].text, undefined);
assert.ok(overwritten.document.edits["proposal-offering"].layout?.title);
const renamed = previewProposalSourceChange(initial, { ...initial.source, businessName: "새 사업명" });
assert.equal(renamed.affected.length, initial.deck.slides.length);
assert.equal(previewProposalSourceChange(initial, initial.source).affected.length, 0);
const imageDocument = structuredClone(initial);
imageDocument.deck.slides.find(slide => slide.id === "proposal-offering")!.image = { id: "approved-fixture", data: "data:image/png;base64,AAAA", alt: "가상 이미지" };
const imagePreview = previewProposalSourceChange(imageDocument, source);
const imageUpdate = approveProposalSourceChange(imageDocument, imagePreview, replacements);
assert.deepEqual(imageUpdate.document.deck.slides.find(slide => slide.id === "proposal-offering")!.image, imageDocument.deck.slides.find(slide => slide.id === "proposal-offering")!.image, "Text rewriting cannot replace or remove the approved image");
assert.equal(previewProposalSourceChange(initial, { ...initial.source, sections: [...initial.source.sections, { chapterTitle: "추가 자료", sectionTitle: "실제 매출", markdown: "새로운 자료" }] }).affected.length, initial.deck.slides.length, "New evidence requires review before dependency mappings exist");
const v3 = upgradeProposalV3(initial);
const offeringPage = v3.pages!.find(page => page.id === "proposal-offering")!;
v3.pages = [{ ...offeringPage, id: "copy-keep" }, ...v3.pages!.filter(page => page.id !== "proposal-commercial"), { ...offeringPage, id: "copy-revise" }, { id: "custom-table", layout: "table" }];
const manualImage = { id: "manual-image", data: "data:image/png;base64,AAAA", alt: "보존할 이미지", width: 100, height: 200, crop: { x: 0, y: 0, w: 1, h: .5 } };
const manualChart = { type: "bar" as const, unit: "건", basis: "actual" as const, source: "사용자가 입력한 기록", categories: ["1월"], series: [{ id: "s1", name: "완료", values: [3] }] };
v3.edits["copy-keep"] = { text: { title: "유지할 복제 문구" }, content: { image: manualImage, chart: manualChart }, layout: { table: { x: 1, y: 3, w: 10, h: 3 } }, alignment: { title: "right" } };
v3.edits["copy-revise"] = { text: { title: "변경할 복제 문구" }, content: { image: manualImage, chart: manualChart }, layout: { title: { x: 1, y: 1, w: 10, h: 1 } }, alignment: { title: "center" } };
v3.deck.slides.find(slide => slide.id === "proposal-offering")!.placement = { title: { x: .8, y: 1, w: 10, h: 1 } };
const beforeV3 = structuredClone(v3), currentV3 = renderableProposal(v3);
const v3Preview = previewProposalSourceChange(v3, source);
assert(!v3Preview.affected.some(slide => slide.slideId === "proposal-commercial"), "Deleted source pages are not change targets");
assert.deepEqual(v3Preview.affected.map(slide => slide.slideId), ["copy-keep", "proposal-summary", "proposal-offering", "copy-revise", "custom-table"]);
assert(v3Preview.affected.filter(slide => ["copy-keep", "copy-revise", "custom-table"].includes(slide.slideId)).every(slide => slide.textConflict));
assert(v3Preview.affected.find(slide => slide.slideId === "custom-table")!.sources.includes("가상 사업 · commercial"));
const targetIds = new Set(v3Preview.affected.map(slide => slide.slideId));
const v3Replacements = currentV3.slides.filter(slide => targetIds.has(slide.id!)).map(slide => ({ ...slide, title: `검토된 ${slide.id}`, lead: "갱신한 조건", sourceSections: ["가상 사업 · commercial"], image: null, chart: null, placement: { title: { x: 0, y: 0, w: 1, h: 1 } } }));
assert.throws(() => approveProposalSourceChange(v3, v3Preview, v3Replacements, { "copy-keep": "keep_manual" }), /manual_text_conflict/);
assert.throws(() => approveProposalSourceChange(v3, v3Preview, [...v3Replacements, initial.deck.slides.find(slide => slide.id === "proposal-commercial")!]), /replacement_mismatch/);
const choices = { "copy-keep": "keep_manual", "copy-revise": "use_revised", "custom-table": "use_revised" } as const;
const v3Applied = approveProposalSourceChange(v3, v3Preview, v3Replacements, choices);
assert.deepEqual(v3Applied.receipt.retainedSlideIds, ["copy-keep", "copy-revise"], "Kept copies and charts preserved by text-only revisions must remain stale");
assert.deepEqual(v3Applied.document.retainedSlideIds, ["copy-keep", "copy-revise"]);
const repeatedPreview = previewProposalSourceChange(v3Applied.document, v3Applied.document.source);
assert.deepEqual(repeatedPreview.affected.map(slide => slide.slideId), ["copy-keep", "copy-revise"], "Retained pages and preserved charts remain reviewable after source dependency changes");
const v3Deck = renderableProposal(v3Applied.document), byId = new Map(v3Deck.slides.map(slide => [slide.id, slide]));
assert.deepEqual(v3Deck.slides.map(slide => slide.id), currentV3.slides.map(slide => slide.id));
assert(!v3Applied.document.deck.slides.some(slide => slide.id === "proposal-commercial"));
assert(v3Applied.document.pages!.every(page => page.sourceId === page.id), "Approval materializes independent page bases without changing public page IDs");
assert.equal(byId.get("copy-keep")!.title, "유지할 복제 문구");
assert.equal(byId.get("copy-keep")!.lead, currentV3.slides[0].lead, "Keeping a copy cannot inherit another page's new lead");
assert.deepEqual(byId.get("copy-keep")!.table, currentV3.slides[0].table);
assert.equal(byId.get("copy-revise")!.title, "검토된 copy-revise");
assert.equal(byId.get("proposal-offering")!.lead, "갱신한 조건");
for (const id of ["copy-keep", "copy-revise"]) {
  assert.deepEqual(byId.get(id)!.image, manualImage);
  assert.deepEqual(byId.get(id)!.chart, manualChart);
  assert.deepEqual(v3Applied.document.edits[id].layout, v3.edits[id].layout);
  assert.deepEqual(v3Applied.document.edits[id].alignment, v3.edits[id].alignment);
}
assert.deepEqual(byId.get("proposal-offering")!.placement, v3.deck.slides.find(slide => slide.id === "proposal-offering")!.placement);
assert.deepEqual(v3, beforeV3);
const v3Undo = undoProposalSourceChange(v3Applied.document, v3Applied.receipt);
assert.deepEqual(v3Undo.pages, v3.pages); assert.deepEqual(v3Undo.deck, v3.deck); assert.deepEqual(v3Undo.edits, v3.edits);
console.log("proposal revision: v2 compatibility, v3 projected/deleted/custom/copy pages, independent approval/keep, visual preservation, source validation, undo and stale revision passed; no AI calls");
